export const supportedLocales = [
  'en',
  'zh-CN',
  'zh-TW',
  'ja',
  'ko',
  'es',
  'fr',
  'de',
  'pt',
  'it',
  'ru',
  'ar',
] as const;
export type AppLocale = typeof supportedLocales[number];

export const localeOptions: ReadonlyArray<{ value: AppLocale; label: string; direction: 'ltr' | 'rtl' }> = [
  { value: 'en', label: 'English', direction: 'ltr' },
  { value: 'zh-CN', label: '简体中文', direction: 'ltr' },
  { value: 'zh-TW', label: '繁體中文', direction: 'ltr' },
  { value: 'ja', label: '日本語', direction: 'ltr' },
  { value: 'ko', label: '한국어', direction: 'ltr' },
  { value: 'es', label: 'Español', direction: 'ltr' },
  { value: 'fr', label: 'Français', direction: 'ltr' },
  { value: 'de', label: 'Deutsch', direction: 'ltr' },
  { value: 'pt', label: 'Português', direction: 'ltr' },
  { value: 'it', label: 'Italiano', direction: 'ltr' },
  { value: 'ru', label: 'Русский', direction: 'ltr' },
  { value: 'ar', label: 'العربية', direction: 'rtl' },
];

export const supportedThemes = ['light', 'warm', 'cool', 'dark-eye'] as const;
export type AppTheme = typeof supportedThemes[number];

export interface AppMenuLabels {
  githubRepository: string;
  starOnGitHub: string;
  watchReleases: string;
  githubDiscussions: string;
  releaseFeedback: string;
  reportOrRequest: string;
  reportBug: string;
  installHelp: string;
  requestFeature: string;
  usageQuestion: string;
  reportDocumentation: string;
  shareReleaseFeedback: string;
  reportCompatibility: string;
  shareSuccessStory: string;
  securityPolicy: string;
  reportPerformance: string;
  reportAccessibility: string;
  reportIssue: string;
  supportGuide: string;
  projectReadme: string;
  installGuide: string;
  privacyAndLocalData: string;
  compatibilityNotes: string;
  troubleshootingGuide: string;
  downloadReleases: string;
  copyShareText: string;
  copyDiagnosticInfo: string;
  revealAppDataFolder: string;
  clearExtractedCache: string;
}

const zhCN = {
  'common.cancel': '取消', 'common.save': '保存', 'common.create': '创建', 'common.back': '返回',
  'library.title': '书库', 'library.all': '全部', 'library.search': '搜索书名或路径', 'library.searchLabel': '搜索书库', 'library.viewMode': '切换展示方式', 'library.grid': '平铺展示', 'library.list': '列表展示', 'library.add': '添加 CHM', 'library.addFiles': '添加 CHM 文件', 'library.collections': '书库分组', 'library.newCollection': '新建书库',
  'library.dropTitle': '松手添加 CHM 文件', 'library.dropSubtitle': '会加入当前选中的书库', 'library.dropInvalidTitle': '请拖入 CHM 文件', 'library.dropInvalidSubtitle': '仅支持 .chm 文档', 'library.emptyTitle': '这个书库还是空的', 'library.emptyDescription': '添加本地 CHM 文件，它们会被加入到当前书库中，随时打开阅读。', 'library.firstUseHelp': '首次使用帮助', 'library.projectReadme': '项目说明', 'library.installGuide': '安装说明', 'library.localData': '本地数据', 'library.troubleshooting': '故障排查', 'library.shortcutHint': '快速添加，也可以拖入 .chm 文件', 'library.noMatches': '没有匹配的文档', 'library.noMatchesDescription': '换个书名、文件夹或路径关键词试试。', 'library.searchHelp': '搜索帮助', 'library.clearSearch': '清空搜索', 'library.usageGuide': '使用说明', 'library.loadFailed': '无法加载书库', 'library.loadFailedDescription': '书库数据暂时无法加载。', 'library.reload': '重新加载',
  'library.documentCount': '{count} 本文档', 'library.filteredCount': '{count} / {total} 本文档', 'library.open': '打开 {name}', 'library.continue': '继续阅读 {name}', 'library.continueLabel': '继续阅读', 'library.sourceMissing': '源文件缺失', 'library.lastOpened': '上次打开 {date}', 'library.addedAt': '添加于 {date}', 'library.remove': '从书库移除', 'library.removeNamed': '从书库移除 {name}', 'library.revealNamed': '在 Finder 中显示 {name}', 'library.reveal': '在 Finder 中显示', 'library.relinkNamed': '重新定位 {name} 的源文件', 'library.relink': '重新定位源文件', 'library.removeConfirm': '从书库移除“{name}”？源文件不会被删除。', 'library.opening': '正在打开...', 'library.openFailed': '无法打开 CHM：{error}', 'library.loadError': '书库数据无法加载：{error}', 'library.importFailed': '无法导入 CHM 文件', 'library.dropImportFailed': '无法导入拖入的 CHM 文件',
  'collection.delete': '删除书库', 'collection.deleteNamed': '删除书库 {name}', 'collection.deleteConfirm': '删除书库“{name}”？', 'collection.deleteMoveConfirm': '删除书库“{name}”后，其中的 {count} 个文档会移动到“全部”（不会删除源文件）。', 'collection.deleteFailed': '无法删除书库', 'collection.rename': '重命名书库', 'collection.create': '新建书库', 'collection.name': '书库名称', 'collection.renameAction': '重命名', 'collection.deleteAction': '删除', 'collection.submitFailed': '无法{action}书库：{error}', 'collection.actionRename': '重命名', 'collection.actionCreate': '创建',
  'reader.currentBook': '当前书籍', 'reader.toggleSidebar': '显示或隐藏目录', 'reader.currentMatches': '当前页面搜索结果', 'reader.previousMatch': '上一个命中', 'reader.nextMatch': '下一个命中', 'reader.previousPage': '上一页', 'reader.nextPage': '下一页', 'reader.back': '后退', 'reader.forward': '前进', 'reader.zoomOut': '缩小正文', 'reader.zoomReset': '重置正文缩放', 'reader.zoomIn': '放大正文', 'reader.encoding': '文本编码', 'reader.defaultEncoding': '默认编码', 'reader.contents': '内容', 'reader.directory': '文档目录', 'reader.treeActions': '目录操作', 'reader.expandAll': '展开全部', 'reader.collapseAll': '收起全部', 'reader.refreshTree': '刷新目录', 'reader.searchScope': '选择搜索范围', 'reader.searchBody': '搜索正文', 'reader.searchDirectory': '搜索目录', 'reader.body': '正文', 'reader.directoryScope': '目录', 'reader.chapters': 'CHM 章节', 'reader.emptyDirectory': '打开 CHM 文件后\n目录将在这里显示', 'reader.resizeSidebar': '调整目录宽度', 'reader.content': '文档正文', 'reader.emptyTitle': '这本文档没有正文', 'reader.emptyDescription': '该 CHM 文件未包含可显示的页面。', 'reader.loading': '正在解析文档...', 'reader.frameTitle': 'CHM 文档内容', 'reader.noDirectory': '此文档未提供目录\n仍可阅读默认页面', 'reader.collapseNamed': '折叠 {name}', 'reader.expandNamed': '展开 {name}', 'reader.progress': '第 {current} / {total} 节', 'reader.topicCount': '共 {count} 节', 'reader.directoryResults': '目录中找到 {count} 项', 'reader.bodyResults': '正文中找到 {count} 处，涉及 {chapters} 个章节', 'reader.searchFailed': '正文搜索失败：{error}', 'reader.encodingFailed': '无法切换文本编码：{error}', 'reader.openTopicFailed': '无法打开章节', 'reader.openExternalFailed': '无法打开外部链接',
  'settings.title': '设置', 'settings.open': '打开设置', 'settings.language': '语言', 'settings.languageDescription': '选择应用界面使用的语言。', 'settings.languageZh': '简体中文', 'settings.languageEn': 'English', 'settings.appearance': '配色主题', 'settings.appearanceDescription': '选择书库、设置和阅读正文的显示配色。',
  'theme.light': '浅白色', 'theme.lightDescription': '清爽明亮的默认配色', 'theme.warm': '暖色', 'theme.warmDescription': '柔和米白与暖橙色', 'theme.cool': '冷色', 'theme.coolDescription': '冷静灰蓝与青绿色', 'theme.darkEye': '黑色护眼', 'theme.darkEyeDescription': '低亮度深色与柔和绿色',
  'error.syncView': '无法同步窗口状态', 'error.reveal': '无法在 Finder 中显示源文件', 'error.relink': '无法重新定位源文件', 'error.remove': '无法从书库移除文档',
} as const;

export type TranslationKey = keyof typeof zhCN;
type TranslationTable = Record<TranslationKey, string>;

const en: TranslationTable = {
  'common.cancel': 'Cancel', 'common.save': 'Save', 'common.create': 'Create', 'common.back': 'Back',
  'library.title': 'Library', 'library.all': 'All', 'library.search': 'Search titles or paths', 'library.searchLabel': 'Search library', 'library.viewMode': 'Change layout', 'library.grid': 'Grid view', 'library.list': 'List view', 'library.add': 'Add CHM', 'library.addFiles': 'Add CHM Files', 'library.collections': 'Library collections', 'library.newCollection': 'New Collection',
  'library.dropTitle': 'Drop CHM files to add', 'library.dropSubtitle': 'Files will be added to the selected collection', 'library.dropInvalidTitle': 'Drop CHM files only', 'library.dropInvalidSubtitle': 'Only .chm documents are supported', 'library.emptyTitle': 'This library is empty', 'library.emptyDescription': 'Add local CHM files to keep them organized and ready to read.', 'library.firstUseHelp': 'Getting started', 'library.projectReadme': 'Project Guide', 'library.installGuide': 'Install Guide', 'library.localData': 'Local Data', 'library.troubleshooting': 'Troubleshooting', 'library.shortcutHint': 'Quick add, or drag .chm files here', 'library.noMatches': 'No matching documents', 'library.noMatchesDescription': 'Try a different title, folder, or path.', 'library.searchHelp': 'Search help', 'library.clearSearch': 'Clear Search', 'library.usageGuide': 'User Guide', 'library.loadFailed': 'Unable to Load Library', 'library.loadFailedDescription': 'Library data is temporarily unavailable.', 'library.reload': 'Reload',
  'library.documentCount': '{count} documents', 'library.filteredCount': '{count} / {total} documents', 'library.open': 'Open {name}', 'library.continue': 'Continue reading {name}', 'library.continueLabel': 'Continue Reading', 'library.sourceMissing': 'Source File Missing', 'library.lastOpened': 'Last opened {date}', 'library.addedAt': 'Added {date}', 'library.remove': 'Remove from Library', 'library.removeNamed': 'Remove {name} from library', 'library.revealNamed': 'Show {name} in Finder', 'library.reveal': 'Show in Finder', 'library.relinkNamed': 'Relink the source file for {name}', 'library.relink': 'Relink Source File', 'library.removeConfirm': 'Remove “{name}” from the library? The source file will not be deleted.', 'library.opening': 'Opening...', 'library.openFailed': 'Unable to open CHM: {error}', 'library.loadError': 'Unable to load library data: {error}', 'library.importFailed': 'Unable to import CHM files', 'library.dropImportFailed': 'Unable to import dropped CHM files',
  'collection.delete': 'Delete Collection', 'collection.deleteNamed': 'Delete collection {name}', 'collection.deleteConfirm': 'Delete collection “{name}”?', 'collection.deleteMoveConfirm': 'Delete collection “{name}”? Its {count} documents will move to All. Source files will not be deleted.', 'collection.deleteFailed': 'Unable to delete collection', 'collection.rename': 'Rename Collection', 'collection.create': 'New Collection', 'collection.name': 'Collection Name', 'collection.renameAction': 'Rename', 'collection.deleteAction': 'Delete', 'collection.submitFailed': 'Unable to {action} collection: {error}', 'collection.actionRename': 'rename', 'collection.actionCreate': 'create',
  'reader.currentBook': 'Current book', 'reader.toggleSidebar': 'Show or hide contents', 'reader.currentMatches': 'Matches on current page', 'reader.previousMatch': 'Previous Match', 'reader.nextMatch': 'Next Match', 'reader.previousPage': 'Previous Topic', 'reader.nextPage': 'Next Topic', 'reader.back': 'Back', 'reader.forward': 'Forward', 'reader.zoomOut': 'Zoom Out', 'reader.zoomReset': 'Actual Size', 'reader.zoomIn': 'Zoom In', 'reader.encoding': 'Text Encoding', 'reader.defaultEncoding': 'Default Encoding', 'reader.contents': 'Contents', 'reader.directory': 'Document contents', 'reader.treeActions': 'Contents Actions', 'reader.expandAll': 'Expand All', 'reader.collapseAll': 'Collapse All', 'reader.refreshTree': 'Refresh Contents', 'reader.searchScope': 'Choose search scope', 'reader.searchBody': 'Search body', 'reader.searchDirectory': 'Search contents', 'reader.body': 'Body', 'reader.directoryScope': 'Contents', 'reader.chapters': 'CHM topics', 'reader.emptyDirectory': 'Open a CHM file to see\nits contents here', 'reader.resizeSidebar': 'Resize contents sidebar', 'reader.content': 'Document body', 'reader.emptyTitle': 'This document has no content', 'reader.emptyDescription': 'This CHM file does not contain a page that can be displayed.', 'reader.loading': 'Parsing document...', 'reader.frameTitle': 'CHM document content', 'reader.noDirectory': 'This document has no contents\nThe default page is still available', 'reader.collapseNamed': 'Collapse {name}', 'reader.expandNamed': 'Expand {name}', 'reader.progress': 'Topic {current} / {total}', 'reader.topicCount': '{count} topics', 'reader.directoryResults': '{count} results in contents', 'reader.bodyResults': '{count} matches across {chapters} topics', 'reader.searchFailed': 'Body search failed: {error}', 'reader.encodingFailed': 'Unable to change text encoding: {error}', 'reader.openTopicFailed': 'Unable to open topic', 'reader.openExternalFailed': 'Unable to open external link',
  'settings.title': 'Settings', 'settings.open': 'Open Settings', 'settings.language': 'Language', 'settings.languageDescription': 'Choose the language used by the application interface.', 'settings.languageZh': '简体中文', 'settings.languageEn': 'English', 'settings.appearance': 'Color Theme', 'settings.appearanceDescription': 'Choose colors for the library, settings, and document reader.',
  'theme.light': 'Light', 'theme.lightDescription': 'Clean, bright default colors', 'theme.warm': 'Warm', 'theme.warmDescription': 'Soft ivory with warm orange', 'theme.cool': 'Cool', 'theme.coolDescription': 'Calm blue-gray with teal', 'theme.darkEye': 'Dark Eye Care', 'theme.darkEyeDescription': 'Low-luminance dark colors with soft green',
  'error.syncView': 'Unable to synchronize window state', 'error.reveal': 'Unable to show source file in Finder', 'error.relink': 'Unable to relink source file', 'error.remove': 'Unable to remove document from library',
};

function defineTranslations(translations: TranslationTable): TranslationTable {
  return translations;
}

function toTraditionalChinese(table: TranslationTable): TranslationTable {
  const replacements: Array<[string, string]> = [
    ['简体中文', '簡體中文'], ['书库', '書庫'], ['文档', '文件'], ['设置', '設定'],
    ['默认', '預設'], ['编码', '編碼'], ['搜索', '搜尋'], ['页面', '頁面'],
    ['显示', '顯示'], ['当前', '目前'], ['打开', '開啟'], ['添加', '加入'],
    ['创建', '建立'], ['删除', '刪除'], ['重命名', '重新命名'], ['选择', '選擇'],
    ['颜色', '顏色'], ['配色', '配色'], ['浅白色', '淺白色'], ['暖色', '暖色'],
    ['冷色', '冷色'], ['护眼', '護眼'], ['点击', '點按'], ['文件夹', '資料夾'],
    ['路径', '路徑'], ['源文件', '來源檔案'], ['重新定位', '重新連結'], ['加载', '載入'],
    ['导入', '匯入'], ['返回', '返回'], ['保存', '儲存'], ['取消', '取消'],
    ['切换', '切換'], ['平铺', '格狀'], ['列表', '列表'], ['松手', '放開'],
    ['仅支持', '僅支援'], ['本地', '本機'], ['随时', '隨時'], ['阅读', '閱讀'],
    ['说明', '說明'], ['安装', '安裝'], ['故障', '疑難'], ['排查', '排解'],
    ['快速', '快速'], ['拖入', '拖入'], ['没有', '沒有'], ['换个', '換個'],
    ['关键词', '關鍵字'], ['清空', '清除'], ['重新', '重新'], ['上次', '上次'],
    ['继续', '繼續'], ['缺失', '遺失'], ['移除', '移除'], ['不会', '不會'],
    ['其中', '其中'], ['移动', '移至'], ['名称', '名稱'], ['无法', '無法'],
    ['正文', '內文'], ['目录', '目錄'], ['上一页', '上一頁'], ['下一页', '下一頁'],
    ['后退', '返回'], ['前进', '前進'], ['缩小', '縮小'], ['放大', '放大'],
    ['重置', '重設'], ['内容', '內容'], ['展开', '展開'], ['收起', '收合'],
    ['刷新', '重新整理'], ['范围', '範圍'], ['章节', '章節'], ['调整', '調整'],
    ['解析', '解析'], ['折叠', '收合'], ['涉及', '涵蓋'], ['切换', '切換'],
    ['外部链接', '外部連結'], ['界面', '介面'], ['应用', '應用程式'], ['柔和', '柔和'],
    ['亮度', '亮度'], ['错误', '錯誤'], ['窗口', '視窗'], ['查找', '尋找'],
    ['项目', '專案'], ['其它', '其他'], ['韩文', '韓文'], ['日文', '日文'],
    ['本文档', '份文件'], ['个文档', '份文件'], ['本文档', '份文件'], ['本书', '本書'],
  ];
  return Object.fromEntries(Object.entries(table).map(([key, value]) => [
    key,
    replacements.reduce((text, [from, to]) => text.replaceAll(from, to), value),
  ])) as TranslationTable;
}

const zhTW = toTraditionalChinese(zhCN);

const ja = defineTranslations({
  'common.cancel': 'キャンセル', 'common.save': '保存', 'common.create': '作成', 'common.back': '戻る',
  'library.title': 'ライブラリ', 'library.all': 'すべて', 'library.search': 'タイトルまたはパスを検索', 'library.searchLabel': 'ライブラリを検索', 'library.viewMode': '表示方法を変更', 'library.grid': 'グリッド表示', 'library.list': 'リスト表示', 'library.add': 'CHMを追加', 'library.addFiles': 'CHMファイルを追加', 'library.collections': 'ライブラリコレクション', 'library.newCollection': '新規コレクション',
  'library.dropTitle': 'CHMファイルをドロップして追加', 'library.dropSubtitle': '選択中のコレクションに追加されます', 'library.dropInvalidTitle': 'CHMファイルをドロップしてください', 'library.dropInvalidSubtitle': '.chm文書のみ対応しています', 'library.emptyTitle': 'ライブラリは空です', 'library.emptyDescription': 'ローカルのCHMファイルを追加して、いつでも読めるよう整理できます。', 'library.firstUseHelp': 'はじめに', 'library.projectReadme': 'プロジェクトガイド', 'library.installGuide': 'インストールガイド', 'library.localData': 'ローカルデータ', 'library.troubleshooting': 'トラブルシューティング', 'library.shortcutHint': 'すばやく追加、または.chmファイルをドロップ', 'library.noMatches': '一致する文書がありません', 'library.noMatchesDescription': '別のタイトル、フォルダ、パスをお試しください。', 'library.searchHelp': '検索ヘルプ', 'library.clearSearch': '検索をクリア', 'library.usageGuide': 'ユーザーガイド', 'library.loadFailed': 'ライブラリを読み込めません', 'library.loadFailedDescription': 'ライブラリデータを一時的に読み込めません。', 'library.reload': '再読み込み',
  'library.documentCount': '{count}件の文書', 'library.filteredCount': '{count} / {total}件の文書', 'library.open': '{name}を開く', 'library.continue': '{name}の続きを読む', 'library.continueLabel': '続きを読む', 'library.sourceMissing': '元ファイルがありません', 'library.lastOpened': '前回開いた日: {date}', 'library.addedAt': '追加日: {date}', 'library.remove': 'ライブラリから削除', 'library.removeNamed': '{name}をライブラリから削除', 'library.revealNamed': '{name}をFinderに表示', 'library.reveal': 'Finderに表示', 'library.relinkNamed': '{name}の元ファイルを再指定', 'library.relink': '元ファイルを再指定', 'library.removeConfirm': '「{name}」をライブラリから削除しますか？元ファイルは削除されません。', 'library.opening': '開いています...', 'library.openFailed': 'CHMを開けません: {error}', 'library.loadError': 'ライブラリデータを読み込めません: {error}', 'library.importFailed': 'CHMファイルを読み込めません', 'library.dropImportFailed': 'ドロップしたCHMファイルを読み込めません',
  'collection.delete': 'コレクションを削除', 'collection.deleteNamed': 'コレクション{name}を削除', 'collection.deleteConfirm': 'コレクション「{name}」を削除しますか？', 'collection.deleteMoveConfirm': 'コレクション「{name}」を削除しますか？{count}件の文書は「すべて」に移動します。元ファイルは削除されません。', 'collection.deleteFailed': 'コレクションを削除できません', 'collection.rename': 'コレクション名を変更', 'collection.create': '新規コレクション', 'collection.name': 'コレクション名', 'collection.renameAction': '名前を変更', 'collection.deleteAction': '削除', 'collection.submitFailed': 'コレクションを{action}できません: {error}', 'collection.actionRename': '名前変更', 'collection.actionCreate': '作成',
  'reader.currentBook': '現在のブック', 'reader.toggleSidebar': '目次を表示または非表示', 'reader.currentMatches': '現在のページの一致項目', 'reader.previousMatch': '前の一致', 'reader.nextMatch': '次の一致', 'reader.previousPage': '前のトピック', 'reader.nextPage': '次のトピック', 'reader.back': '戻る', 'reader.forward': '進む', 'reader.zoomOut': '本文を縮小', 'reader.zoomReset': '実際のサイズ', 'reader.zoomIn': '本文を拡大', 'reader.encoding': 'テキストエンコーディング', 'reader.defaultEncoding': '既定のエンコーディング', 'reader.contents': '目次', 'reader.directory': '文書の目次', 'reader.treeActions': '目次の操作', 'reader.expandAll': 'すべて展開', 'reader.collapseAll': 'すべて折りたたむ', 'reader.refreshTree': '目次を更新', 'reader.searchScope': '検索範囲を選択', 'reader.searchBody': '本文を検索', 'reader.searchDirectory': '目次を検索', 'reader.body': '本文', 'reader.directoryScope': '目次', 'reader.chapters': 'CHMトピック', 'reader.emptyDirectory': 'CHMファイルを開くと\nここに目次が表示されます', 'reader.resizeSidebar': '目次サイドバーの幅を変更', 'reader.content': '文書本文', 'reader.emptyTitle': 'この文書には本文がありません', 'reader.emptyDescription': 'このCHMファイルには表示できるページがありません。', 'reader.loading': '文書を解析しています...', 'reader.frameTitle': 'CHM文書の内容', 'reader.noDirectory': 'この文書には目次がありません\n既定のページは閲覧できます', 'reader.collapseNamed': '{name}を折りたたむ', 'reader.expandNamed': '{name}を展開', 'reader.progress': '{current} / {total} トピック', 'reader.topicCount': '全{count}トピック', 'reader.directoryResults': '目次に{count}件', 'reader.bodyResults': '{chapters}トピックで{count}件一致', 'reader.searchFailed': '本文検索に失敗しました: {error}', 'reader.encodingFailed': 'エンコーディングを変更できません: {error}', 'reader.openTopicFailed': 'トピックを開けません', 'reader.openExternalFailed': '外部リンクを開けません',
  'settings.title': '設定', 'settings.open': '設定を開く', 'settings.language': '言語', 'settings.languageDescription': 'アプリケーション画面で使用する言語を選択します。', 'settings.languageZh': '簡体字中国語', 'settings.languageEn': '英語', 'settings.appearance': 'カラーテーマ', 'settings.appearanceDescription': 'ライブラリ、設定、文書リーダーの配色を選択します。',
  'theme.light': 'ライト', 'theme.lightDescription': '明るくすっきりした既定の配色', 'theme.warm': 'ウォーム', 'theme.warmDescription': '柔らかなアイボリーと暖色のオレンジ', 'theme.cool': 'クール', 'theme.coolDescription': '落ち着いた青灰色とティール', 'theme.darkEye': 'ダーク・アイケア', 'theme.darkEyeDescription': '低輝度の濃色と柔らかな緑',
  'error.syncView': 'ウインドウ状態を同期できません', 'error.reveal': '元ファイルをFinderに表示できません', 'error.relink': '元ファイルを再指定できません', 'error.remove': '文書をライブラリから削除できません',
});

const ko = defineTranslations({
  'common.cancel': '취소', 'common.save': '저장', 'common.create': '생성', 'common.back': '뒤로',
  'library.title': '보관함', 'library.all': '전체', 'library.search': '제목 또는 경로 검색', 'library.searchLabel': '보관함 검색', 'library.viewMode': '보기 방식 변경', 'library.grid': '격자 보기', 'library.list': '목록 보기', 'library.add': 'CHM 추가', 'library.addFiles': 'CHM 파일 추가', 'library.collections': '보관함 컬렉션', 'library.newCollection': '새 컬렉션',
  'library.dropTitle': 'CHM 파일을 놓아 추가', 'library.dropSubtitle': '선택한 컬렉션에 추가됩니다', 'library.dropInvalidTitle': 'CHM 파일을 놓아 주세요', 'library.dropInvalidSubtitle': '.chm 문서만 지원합니다', 'library.emptyTitle': '보관함이 비어 있습니다', 'library.emptyDescription': '로컬 CHM 파일을 추가해 정리하고 언제든 읽을 수 있습니다.', 'library.firstUseHelp': '시작하기', 'library.projectReadme': '프로젝트 안내', 'library.installGuide': '설치 안내', 'library.localData': '로컬 데이터', 'library.troubleshooting': '문제 해결', 'library.shortcutHint': '빠른 추가 또는 .chm 파일 끌어놓기', 'library.noMatches': '일치하는 문서가 없습니다', 'library.noMatchesDescription': '다른 제목, 폴더 또는 경로를 검색해 보세요.', 'library.searchHelp': '검색 도움말', 'library.clearSearch': '검색 지우기', 'library.usageGuide': '사용 안내', 'library.loadFailed': '보관함을 불러올 수 없음', 'library.loadFailedDescription': '보관함 데이터를 일시적으로 사용할 수 없습니다.', 'library.reload': '다시 불러오기',
  'library.documentCount': '문서 {count}개', 'library.filteredCount': '문서 {count} / {total}개', 'library.open': '{name} 열기', 'library.continue': '{name} 계속 읽기', 'library.continueLabel': '계속 읽기', 'library.sourceMissing': '원본 파일 없음', 'library.lastOpened': '마지막으로 연 날짜 {date}', 'library.addedAt': '추가한 날짜 {date}', 'library.remove': '보관함에서 제거', 'library.removeNamed': '{name} 보관함에서 제거', 'library.revealNamed': 'Finder에서 {name} 보기', 'library.reveal': 'Finder에서 보기', 'library.relinkNamed': '{name} 원본 파일 다시 연결', 'library.relink': '원본 파일 다시 연결', 'library.removeConfirm': '보관함에서 “{name}”을(를) 제거할까요? 원본 파일은 삭제되지 않습니다.', 'library.opening': '여는 중...', 'library.openFailed': 'CHM을 열 수 없습니다: {error}', 'library.loadError': '보관함 데이터를 불러올 수 없습니다: {error}', 'library.importFailed': 'CHM 파일을 가져올 수 없습니다', 'library.dropImportFailed': '놓은 CHM 파일을 가져올 수 없습니다',
  'collection.delete': '컬렉션 삭제', 'collection.deleteNamed': '{name} 컬렉션 삭제', 'collection.deleteConfirm': '“{name}” 컬렉션을 삭제할까요?', 'collection.deleteMoveConfirm': '“{name}” 컬렉션을 삭제할까요? 문서 {count}개가 전체로 이동합니다. 원본 파일은 삭제되지 않습니다.', 'collection.deleteFailed': '컬렉션을 삭제할 수 없습니다', 'collection.rename': '컬렉션 이름 변경', 'collection.create': '새 컬렉션', 'collection.name': '컬렉션 이름', 'collection.renameAction': '이름 변경', 'collection.deleteAction': '삭제', 'collection.submitFailed': '컬렉션을 {action}할 수 없습니다: {error}', 'collection.actionRename': '이름 변경', 'collection.actionCreate': '생성',
  'reader.currentBook': '현재 책', 'reader.toggleSidebar': '목차 표시 또는 숨기기', 'reader.currentMatches': '현재 페이지 검색 결과', 'reader.previousMatch': '이전 결과', 'reader.nextMatch': '다음 결과', 'reader.previousPage': '이전 주제', 'reader.nextPage': '다음 주제', 'reader.back': '뒤로', 'reader.forward': '앞으로', 'reader.zoomOut': '본문 축소', 'reader.zoomReset': '실제 크기', 'reader.zoomIn': '본문 확대', 'reader.encoding': '텍스트 인코딩', 'reader.defaultEncoding': '기본 인코딩', 'reader.contents': '목차', 'reader.directory': '문서 목차', 'reader.treeActions': '목차 동작', 'reader.expandAll': '모두 펼치기', 'reader.collapseAll': '모두 접기', 'reader.refreshTree': '목차 새로 고침', 'reader.searchScope': '검색 범위 선택', 'reader.searchBody': '본문 검색', 'reader.searchDirectory': '목차 검색', 'reader.body': '본문', 'reader.directoryScope': '목차', 'reader.chapters': 'CHM 주제', 'reader.emptyDirectory': 'CHM 파일을 열면\n여기에 목차가 표시됩니다', 'reader.resizeSidebar': '목차 사이드바 크기 조절', 'reader.content': '문서 본문', 'reader.emptyTitle': '이 문서에는 본문이 없습니다', 'reader.emptyDescription': '이 CHM 파일에는 표시할 수 있는 페이지가 없습니다.', 'reader.loading': '문서 분석 중...', 'reader.frameTitle': 'CHM 문서 내용', 'reader.noDirectory': '이 문서에는 목차가 없습니다\n기본 페이지는 읽을 수 있습니다', 'reader.collapseNamed': '{name} 접기', 'reader.expandNamed': '{name} 펼치기', 'reader.progress': '{current} / {total} 주제', 'reader.topicCount': '주제 {count}개', 'reader.directoryResults': '목차에서 {count}개 찾음', 'reader.bodyResults': '주제 {chapters}개에서 {count}개 찾음', 'reader.searchFailed': '본문 검색 실패: {error}', 'reader.encodingFailed': '텍스트 인코딩을 변경할 수 없습니다: {error}', 'reader.openTopicFailed': '주제를 열 수 없습니다', 'reader.openExternalFailed': '외부 링크를 열 수 없습니다',
  'settings.title': '설정', 'settings.open': '설정 열기', 'settings.language': '언어', 'settings.languageDescription': '앱 인터페이스에서 사용할 언어를 선택합니다.', 'settings.languageZh': '중국어 간체', 'settings.languageEn': '영어', 'settings.appearance': '색상 테마', 'settings.appearanceDescription': '보관함, 설정 및 문서 리더의 색상을 선택합니다.',
  'theme.light': '라이트', 'theme.lightDescription': '깨끗하고 밝은 기본 색상', 'theme.warm': '따뜻한 색', 'theme.warmDescription': '부드러운 아이보리와 따뜻한 주황', 'theme.cool': '차가운 색', 'theme.coolDescription': '차분한 청회색과 청록색', 'theme.darkEye': '어두운 눈 보호', 'theme.darkEyeDescription': '낮은 밝기의 어두운 색과 부드러운 녹색',
  'error.syncView': '창 상태를 동기화할 수 없습니다', 'error.reveal': 'Finder에서 원본 파일을 표시할 수 없습니다', 'error.relink': '원본 파일을 다시 연결할 수 없습니다', 'error.remove': '보관함에서 문서를 제거할 수 없습니다',
});

const es = defineTranslations({
  'common.cancel': 'Cancelar', 'common.save': 'Guardar', 'common.create': 'Crear', 'common.back': 'Volver',
  'library.title': 'Biblioteca', 'library.all': 'Todo', 'library.search': 'Buscar títulos o rutas', 'library.searchLabel': 'Buscar en la biblioteca', 'library.viewMode': 'Cambiar vista', 'library.grid': 'Vista de cuadrícula', 'library.list': 'Vista de lista', 'library.add': 'Añadir CHM', 'library.addFiles': 'Añadir archivos CHM', 'library.collections': 'Colecciones de la biblioteca', 'library.newCollection': 'Nueva colección',
  'library.dropTitle': 'Suelta archivos CHM para añadirlos', 'library.dropSubtitle': 'Se añadirán a la colección seleccionada', 'library.dropInvalidTitle': 'Suelta solo archivos CHM', 'library.dropInvalidSubtitle': 'Solo se admiten documentos .chm', 'library.emptyTitle': 'Esta biblioteca está vacía', 'library.emptyDescription': 'Añade archivos CHM locales para organizarlos y leerlos cuando quieras.', 'library.firstUseHelp': 'Primeros pasos', 'library.projectReadme': 'Guía del proyecto', 'library.installGuide': 'Guía de instalación', 'library.localData': 'Datos locales', 'library.troubleshooting': 'Solución de problemas', 'library.shortcutHint': 'Añade rápidamente o arrastra archivos .chm aquí', 'library.noMatches': 'No hay documentos coincidentes', 'library.noMatchesDescription': 'Prueba con otro título, carpeta o ruta.', 'library.searchHelp': 'Ayuda de búsqueda', 'library.clearSearch': 'Borrar búsqueda', 'library.usageGuide': 'Guía de uso', 'library.loadFailed': 'No se pudo cargar la biblioteca', 'library.loadFailedDescription': 'Los datos de la biblioteca no están disponibles temporalmente.', 'library.reload': 'Volver a cargar',
  'library.documentCount': '{count} documentos', 'library.filteredCount': '{count} de {total} documentos', 'library.open': 'Abrir {name}', 'library.continue': 'Seguir leyendo {name}', 'library.continueLabel': 'Seguir leyendo', 'library.sourceMissing': 'Falta el archivo original', 'library.lastOpened': 'Última apertura: {date}', 'library.addedAt': 'Añadido: {date}', 'library.remove': 'Quitar de la biblioteca', 'library.removeNamed': 'Quitar {name} de la biblioteca', 'library.revealNamed': 'Mostrar {name} en Finder', 'library.reveal': 'Mostrar en Finder', 'library.relinkNamed': 'Volver a vincular el archivo de {name}', 'library.relink': 'Volver a vincular archivo', 'library.removeConfirm': '¿Quitar “{name}” de la biblioteca? El archivo original no se eliminará.', 'library.opening': 'Abriendo...', 'library.openFailed': 'No se pudo abrir el CHM: {error}', 'library.loadError': 'No se pudieron cargar los datos de la biblioteca: {error}', 'library.importFailed': 'No se pudieron importar los archivos CHM', 'library.dropImportFailed': 'No se pudieron importar los archivos CHM arrastrados',
  'collection.delete': 'Eliminar colección', 'collection.deleteNamed': 'Eliminar la colección {name}', 'collection.deleteConfirm': '¿Eliminar la colección “{name}”?', 'collection.deleteMoveConfirm': '¿Eliminar la colección “{name}”? Sus {count} documentos se moverán a Todo. Los archivos originales no se eliminarán.', 'collection.deleteFailed': 'No se pudo eliminar la colección', 'collection.rename': 'Renombrar colección', 'collection.create': 'Nueva colección', 'collection.name': 'Nombre de la colección', 'collection.renameAction': 'Renombrar', 'collection.deleteAction': 'Eliminar', 'collection.submitFailed': 'No se pudo {action} la colección: {error}', 'collection.actionRename': 'renombrar', 'collection.actionCreate': 'crear',
  'reader.currentBook': 'Libro actual', 'reader.toggleSidebar': 'Mostrar u ocultar el índice', 'reader.currentMatches': 'Coincidencias en la página actual', 'reader.previousMatch': 'Coincidencia anterior', 'reader.nextMatch': 'Coincidencia siguiente', 'reader.previousPage': 'Tema anterior', 'reader.nextPage': 'Tema siguiente', 'reader.back': 'Atrás', 'reader.forward': 'Adelante', 'reader.zoomOut': 'Reducir texto', 'reader.zoomReset': 'Tamaño real', 'reader.zoomIn': 'Ampliar texto', 'reader.encoding': 'Codificación de texto', 'reader.defaultEncoding': 'Codificación predeterminada', 'reader.contents': 'Contenido', 'reader.directory': 'Índice del documento', 'reader.treeActions': 'Acciones del índice', 'reader.expandAll': 'Expandir todo', 'reader.collapseAll': 'Contraer todo', 'reader.refreshTree': 'Actualizar índice', 'reader.searchScope': 'Elegir ámbito de búsqueda', 'reader.searchBody': 'Buscar en el texto', 'reader.searchDirectory': 'Buscar en el índice', 'reader.body': 'Texto', 'reader.directoryScope': 'Índice', 'reader.chapters': 'Temas CHM', 'reader.emptyDirectory': 'Abre un archivo CHM para ver\nsu índice aquí', 'reader.resizeSidebar': 'Cambiar tamaño de la barra lateral', 'reader.content': 'Contenido del documento', 'reader.emptyTitle': 'Este documento no tiene contenido', 'reader.emptyDescription': 'Este archivo CHM no contiene una página que se pueda mostrar.', 'reader.loading': 'Analizando documento...', 'reader.frameTitle': 'Contenido del documento CHM', 'reader.noDirectory': 'Este documento no tiene índice\nLa página predeterminada sigue disponible', 'reader.collapseNamed': 'Contraer {name}', 'reader.expandNamed': 'Expandir {name}', 'reader.progress': 'Tema {current} de {total}', 'reader.topicCount': '{count} temas', 'reader.directoryResults': '{count} resultados en el índice', 'reader.bodyResults': '{count} coincidencias en {chapters} temas', 'reader.searchFailed': 'Falló la búsqueda en el texto: {error}', 'reader.encodingFailed': 'No se pudo cambiar la codificación: {error}', 'reader.openTopicFailed': 'No se pudo abrir el tema', 'reader.openExternalFailed': 'No se pudo abrir el enlace externo',
  'settings.title': 'Ajustes', 'settings.open': 'Abrir Ajustes', 'settings.language': 'Idioma', 'settings.languageDescription': 'Elige el idioma de la interfaz de la aplicación.', 'settings.languageZh': 'Chino simplificado', 'settings.languageEn': 'Inglés', 'settings.appearance': 'Tema de color', 'settings.appearanceDescription': 'Elige los colores de la biblioteca, los ajustes y el lector.',
  'theme.light': 'Claro', 'theme.lightDescription': 'Colores predeterminados limpios y luminosos', 'theme.warm': 'Cálido', 'theme.warmDescription': 'Marfil suave con naranja cálido', 'theme.cool': 'Frío', 'theme.coolDescription': 'Gris azulado sereno con verde azulado', 'theme.darkEye': 'Oscuro para la vista', 'theme.darkEyeDescription': 'Colores oscuros de baja luminosidad con verde suave',
  'error.syncView': 'No se pudo sincronizar el estado de la ventana', 'error.reveal': 'No se pudo mostrar el archivo original en Finder', 'error.relink': 'No se pudo volver a vincular el archivo original', 'error.remove': 'No se pudo quitar el documento de la biblioteca',
});

const fr = defineTranslations({
  'common.cancel': 'Annuler', 'common.save': 'Enregistrer', 'common.create': 'Créer', 'common.back': 'Retour',
  'library.title': 'Bibliothèque', 'library.all': 'Tout', 'library.search': 'Rechercher un titre ou un chemin', 'library.searchLabel': 'Rechercher dans la bibliothèque', 'library.viewMode': 'Changer de présentation', 'library.grid': 'Vue en grille', 'library.list': 'Vue en liste', 'library.add': 'Ajouter un CHM', 'library.addFiles': 'Ajouter des fichiers CHM', 'library.collections': 'Collections de la bibliothèque', 'library.newCollection': 'Nouvelle collection',
  'library.dropTitle': 'Déposez des fichiers CHM pour les ajouter', 'library.dropSubtitle': 'Ils seront ajoutés à la collection sélectionnée', 'library.dropInvalidTitle': 'Déposez uniquement des fichiers CHM', 'library.dropInvalidSubtitle': 'Seuls les documents .chm sont pris en charge', 'library.emptyTitle': 'Cette bibliothèque est vide', 'library.emptyDescription': 'Ajoutez des fichiers CHM locaux pour les organiser et les lire à tout moment.', 'library.firstUseHelp': 'Bien démarrer', 'library.projectReadme': 'Guide du projet', 'library.installGuide': 'Guide d’installation', 'library.localData': 'Données locales', 'library.troubleshooting': 'Dépannage', 'library.shortcutHint': 'Ajout rapide ou glissez des fichiers .chm ici', 'library.noMatches': 'Aucun document correspondant', 'library.noMatchesDescription': 'Essayez un autre titre, dossier ou chemin.', 'library.searchHelp': 'Aide à la recherche', 'library.clearSearch': 'Effacer la recherche', 'library.usageGuide': 'Guide d’utilisation', 'library.loadFailed': 'Impossible de charger la bibliothèque', 'library.loadFailedDescription': 'Les données de la bibliothèque sont temporairement indisponibles.', 'library.reload': 'Recharger',
  'library.documentCount': '{count} documents', 'library.filteredCount': '{count} sur {total} documents', 'library.open': 'Ouvrir {name}', 'library.continue': 'Continuer la lecture de {name}', 'library.continueLabel': 'Continuer la lecture', 'library.sourceMissing': 'Fichier source manquant', 'library.lastOpened': 'Dernière ouverture : {date}', 'library.addedAt': 'Ajouté le {date}', 'library.remove': 'Retirer de la bibliothèque', 'library.removeNamed': 'Retirer {name} de la bibliothèque', 'library.revealNamed': 'Afficher {name} dans le Finder', 'library.reveal': 'Afficher dans le Finder', 'library.relinkNamed': 'Relier le fichier source de {name}', 'library.relink': 'Relier le fichier source', 'library.removeConfirm': 'Retirer « {name} » de la bibliothèque ? Le fichier source ne sera pas supprimé.', 'library.opening': 'Ouverture...', 'library.openFailed': 'Impossible d’ouvrir le CHM : {error}', 'library.loadError': 'Impossible de charger les données de la bibliothèque : {error}', 'library.importFailed': 'Impossible d’importer les fichiers CHM', 'library.dropImportFailed': 'Impossible d’importer les fichiers CHM déposés',
  'collection.delete': 'Supprimer la collection', 'collection.deleteNamed': 'Supprimer la collection {name}', 'collection.deleteConfirm': 'Supprimer la collection « {name} » ?', 'collection.deleteMoveConfirm': 'Supprimer la collection « {name} » ? Ses {count} documents seront déplacés vers Tout. Les fichiers source ne seront pas supprimés.', 'collection.deleteFailed': 'Impossible de supprimer la collection', 'collection.rename': 'Renommer la collection', 'collection.create': 'Nouvelle collection', 'collection.name': 'Nom de la collection', 'collection.renameAction': 'Renommer', 'collection.deleteAction': 'Supprimer', 'collection.submitFailed': 'Impossible de {action} la collection : {error}', 'collection.actionRename': 'renommer', 'collection.actionCreate': 'créer',
  'reader.currentBook': 'Livre actuel', 'reader.toggleSidebar': 'Afficher ou masquer le sommaire', 'reader.currentMatches': 'Résultats sur la page actuelle', 'reader.previousMatch': 'Résultat précédent', 'reader.nextMatch': 'Résultat suivant', 'reader.previousPage': 'Sujet précédent', 'reader.nextPage': 'Sujet suivant', 'reader.back': 'Retour', 'reader.forward': 'Avancer', 'reader.zoomOut': 'Réduire le texte', 'reader.zoomReset': 'Taille réelle', 'reader.zoomIn': 'Agrandir le texte', 'reader.encoding': 'Encodage du texte', 'reader.defaultEncoding': 'Encodage par défaut', 'reader.contents': 'Sommaire', 'reader.directory': 'Sommaire du document', 'reader.treeActions': 'Actions du sommaire', 'reader.expandAll': 'Tout développer', 'reader.collapseAll': 'Tout réduire', 'reader.refreshTree': 'Actualiser le sommaire', 'reader.searchScope': 'Choisir la zone de recherche', 'reader.searchBody': 'Rechercher dans le texte', 'reader.searchDirectory': 'Rechercher dans le sommaire', 'reader.body': 'Texte', 'reader.directoryScope': 'Sommaire', 'reader.chapters': 'Sujets CHM', 'reader.emptyDirectory': 'Ouvrez un fichier CHM pour afficher\nson sommaire ici', 'reader.resizeSidebar': 'Redimensionner la barre latérale', 'reader.content': 'Contenu du document', 'reader.emptyTitle': 'Ce document ne contient aucun contenu', 'reader.emptyDescription': 'Ce fichier CHM ne contient aucune page affichable.', 'reader.loading': 'Analyse du document...', 'reader.frameTitle': 'Contenu du document CHM', 'reader.noDirectory': 'Ce document ne contient aucun sommaire\nLa page par défaut reste disponible', 'reader.collapseNamed': 'Réduire {name}', 'reader.expandNamed': 'Développer {name}', 'reader.progress': 'Sujet {current} sur {total}', 'reader.topicCount': '{count} sujets', 'reader.directoryResults': '{count} résultats dans le sommaire', 'reader.bodyResults': '{count} résultats dans {chapters} sujets', 'reader.searchFailed': 'Échec de la recherche dans le texte : {error}', 'reader.encodingFailed': 'Impossible de changer l’encodage : {error}', 'reader.openTopicFailed': 'Impossible d’ouvrir le sujet', 'reader.openExternalFailed': 'Impossible d’ouvrir le lien externe',
  'settings.title': 'Réglages', 'settings.open': 'Ouvrir les réglages', 'settings.language': 'Langue', 'settings.languageDescription': 'Choisissez la langue de l’interface de l’application.', 'settings.languageZh': 'Chinois simplifié', 'settings.languageEn': 'Anglais', 'settings.appearance': 'Thème de couleurs', 'settings.appearanceDescription': 'Choisissez les couleurs de la bibliothèque, des réglages et du lecteur.',
  'theme.light': 'Clair', 'theme.lightDescription': 'Couleurs claires et lumineuses par défaut', 'theme.warm': 'Chaud', 'theme.warmDescription': 'Ivoire doux et orange chaud', 'theme.cool': 'Froid', 'theme.coolDescription': 'Bleu-gris calme et sarcelle', 'theme.darkEye': 'Sombre reposant', 'theme.darkEyeDescription': 'Couleurs sombres à faible luminosité et vert doux',
  'error.syncView': 'Impossible de synchroniser l’état de la fenêtre', 'error.reveal': 'Impossible d’afficher le fichier source dans le Finder', 'error.relink': 'Impossible de relier le fichier source', 'error.remove': 'Impossible de retirer le document de la bibliothèque',
});

const de = defineTranslations({
  'common.cancel': 'Abbrechen', 'common.save': 'Sichern', 'common.create': 'Erstellen', 'common.back': 'Zurück',
  'library.title': 'Mediathek', 'library.all': 'Alle', 'library.search': 'Titel oder Pfade suchen', 'library.searchLabel': 'Mediathek durchsuchen', 'library.viewMode': 'Darstellung ändern', 'library.grid': 'Rasteransicht', 'library.list': 'Listenansicht', 'library.add': 'CHM hinzufügen', 'library.addFiles': 'CHM-Dateien hinzufügen', 'library.collections': 'Mediathek-Sammlungen', 'library.newCollection': 'Neue Sammlung',
  'library.dropTitle': 'CHM-Dateien zum Hinzufügen ablegen', 'library.dropSubtitle': 'Sie werden der ausgewählten Sammlung hinzugefügt', 'library.dropInvalidTitle': 'Nur CHM-Dateien ablegen', 'library.dropInvalidSubtitle': 'Nur .chm-Dokumente werden unterstützt', 'library.emptyTitle': 'Diese Mediathek ist leer', 'library.emptyDescription': 'Füge lokale CHM-Dateien hinzu, um sie zu ordnen und jederzeit zu lesen.', 'library.firstUseHelp': 'Erste Schritte', 'library.projectReadme': 'Projektanleitung', 'library.installGuide': 'Installationsanleitung', 'library.localData': 'Lokale Daten', 'library.troubleshooting': 'Fehlerbehebung', 'library.shortcutHint': 'Schnell hinzufügen oder .chm-Dateien hierher ziehen', 'library.noMatches': 'Keine passenden Dokumente', 'library.noMatchesDescription': 'Versuche einen anderen Titel, Ordner oder Pfad.', 'library.searchHelp': 'Suchhilfe', 'library.clearSearch': 'Suche löschen', 'library.usageGuide': 'Benutzerhandbuch', 'library.loadFailed': 'Mediathek kann nicht geladen werden', 'library.loadFailedDescription': 'Die Mediathekdaten sind vorübergehend nicht verfügbar.', 'library.reload': 'Neu laden',
  'library.documentCount': '{count} Dokumente', 'library.filteredCount': '{count} von {total} Dokumenten', 'library.open': '{name} öffnen', 'library.continue': '{name} weiterlesen', 'library.continueLabel': 'Weiterlesen', 'library.sourceMissing': 'Quelldatei fehlt', 'library.lastOpened': 'Zuletzt geöffnet: {date}', 'library.addedAt': 'Hinzugefügt: {date}', 'library.remove': 'Aus Mediathek entfernen', 'library.removeNamed': '{name} aus Mediathek entfernen', 'library.revealNamed': '{name} im Finder zeigen', 'library.reveal': 'Im Finder zeigen', 'library.relinkNamed': 'Quelldatei für {name} neu verknüpfen', 'library.relink': 'Quelldatei neu verknüpfen', 'library.removeConfirm': '„{name}“ aus der Mediathek entfernen? Die Quelldatei wird nicht gelöscht.', 'library.opening': 'Wird geöffnet...', 'library.openFailed': 'CHM kann nicht geöffnet werden: {error}', 'library.loadError': 'Mediathekdaten können nicht geladen werden: {error}', 'library.importFailed': 'CHM-Dateien können nicht importiert werden', 'library.dropImportFailed': 'Abgelegte CHM-Dateien können nicht importiert werden',
  'collection.delete': 'Sammlung löschen', 'collection.deleteNamed': 'Sammlung {name} löschen', 'collection.deleteConfirm': 'Sammlung „{name}“ löschen?', 'collection.deleteMoveConfirm': 'Sammlung „{name}“ löschen? Ihre {count} Dokumente werden nach Alle verschoben. Quelldateien werden nicht gelöscht.', 'collection.deleteFailed': 'Sammlung kann nicht gelöscht werden', 'collection.rename': 'Sammlung umbenennen', 'collection.create': 'Neue Sammlung', 'collection.name': 'Sammlungsname', 'collection.renameAction': 'Umbenennen', 'collection.deleteAction': 'Löschen', 'collection.submitFailed': 'Sammlung kann nicht {action} werden: {error}', 'collection.actionRename': 'umbenannt', 'collection.actionCreate': 'erstellt',
  'reader.currentBook': 'Aktuelles Buch', 'reader.toggleSidebar': 'Inhaltsverzeichnis ein- oder ausblenden', 'reader.currentMatches': 'Treffer auf der aktuellen Seite', 'reader.previousMatch': 'Vorheriger Treffer', 'reader.nextMatch': 'Nächster Treffer', 'reader.previousPage': 'Vorheriges Thema', 'reader.nextPage': 'Nächstes Thema', 'reader.back': 'Zurück', 'reader.forward': 'Vorwärts', 'reader.zoomOut': 'Text verkleinern', 'reader.zoomReset': 'Tatsächliche Größe', 'reader.zoomIn': 'Text vergrößern', 'reader.encoding': 'Textcodierung', 'reader.defaultEncoding': 'Standardcodierung', 'reader.contents': 'Inhalt', 'reader.directory': 'Dokumentinhalt', 'reader.treeActions': 'Inhaltsaktionen', 'reader.expandAll': 'Alle erweitern', 'reader.collapseAll': 'Alle reduzieren', 'reader.refreshTree': 'Inhalt aktualisieren', 'reader.searchScope': 'Suchbereich auswählen', 'reader.searchBody': 'Text durchsuchen', 'reader.searchDirectory': 'Inhalt durchsuchen', 'reader.body': 'Text', 'reader.directoryScope': 'Inhalt', 'reader.chapters': 'CHM-Themen', 'reader.emptyDirectory': 'Öffne eine CHM-Datei, um\nihren Inhalt hier zu sehen', 'reader.resizeSidebar': 'Inhaltsseitenleiste skalieren', 'reader.content': 'Dokumentinhalt', 'reader.emptyTitle': 'Dieses Dokument hat keinen Inhalt', 'reader.emptyDescription': 'Diese CHM-Datei enthält keine darstellbare Seite.', 'reader.loading': 'Dokument wird analysiert...', 'reader.frameTitle': 'CHM-Dokumentinhalt', 'reader.noDirectory': 'Dieses Dokument hat kein Inhaltsverzeichnis\nDie Standardseite bleibt verfügbar', 'reader.collapseNamed': '{name} reduzieren', 'reader.expandNamed': '{name} erweitern', 'reader.progress': 'Thema {current} von {total}', 'reader.topicCount': '{count} Themen', 'reader.directoryResults': '{count} Ergebnisse im Inhalt', 'reader.bodyResults': '{count} Treffer in {chapters} Themen', 'reader.searchFailed': 'Textsuche fehlgeschlagen: {error}', 'reader.encodingFailed': 'Textcodierung kann nicht geändert werden: {error}', 'reader.openTopicFailed': 'Thema kann nicht geöffnet werden', 'reader.openExternalFailed': 'Externer Link kann nicht geöffnet werden',
  'settings.title': 'Einstellungen', 'settings.open': 'Einstellungen öffnen', 'settings.language': 'Sprache', 'settings.languageDescription': 'Wähle die Sprache der Programmoberfläche.', 'settings.languageZh': 'Vereinfachtes Chinesisch', 'settings.languageEn': 'Englisch', 'settings.appearance': 'Farbthema', 'settings.appearanceDescription': 'Wähle Farben für Mediathek, Einstellungen und Dokumentleser.',
  'theme.light': 'Hell', 'theme.lightDescription': 'Klare, helle Standardfarben', 'theme.warm': 'Warm', 'theme.warmDescription': 'Sanftes Elfenbein mit warmem Orange', 'theme.cool': 'Kühl', 'theme.coolDescription': 'Ruhiges Blaugrau mit Türkis', 'theme.darkEye': 'Dunkel und augenschonend', 'theme.darkEyeDescription': 'Dunkle Farben mit niedriger Helligkeit und sanftem Grün',
  'error.syncView': 'Fensterstatus kann nicht synchronisiert werden', 'error.reveal': 'Quelldatei kann nicht im Finder gezeigt werden', 'error.relink': 'Quelldatei kann nicht neu verknüpft werden', 'error.remove': 'Dokument kann nicht aus der Mediathek entfernt werden',
});

const pt = defineTranslations({
  'common.cancel': 'Cancelar', 'common.save': 'Guardar', 'common.create': 'Criar', 'common.back': 'Voltar',
  'library.title': 'Biblioteca', 'library.all': 'Tudo', 'library.search': 'Pesquisar títulos ou caminhos', 'library.searchLabel': 'Pesquisar na biblioteca', 'library.viewMode': 'Alterar visualização', 'library.grid': 'Vista em grelha', 'library.list': 'Vista em lista', 'library.add': 'Adicionar CHM', 'library.addFiles': 'Adicionar ficheiros CHM', 'library.collections': 'Coleções da biblioteca', 'library.newCollection': 'Nova coleção',
  'library.dropTitle': 'Largue ficheiros CHM para adicionar', 'library.dropSubtitle': 'Serão adicionados à coleção selecionada', 'library.dropInvalidTitle': 'Largue apenas ficheiros CHM', 'library.dropInvalidSubtitle': 'Apenas documentos .chm são suportados', 'library.emptyTitle': 'Esta biblioteca está vazia', 'library.emptyDescription': 'Adicione ficheiros CHM locais para os organizar e ler a qualquer momento.', 'library.firstUseHelp': 'Primeiros passos', 'library.projectReadme': 'Guia do projeto', 'library.installGuide': 'Guia de instalação', 'library.localData': 'Dados locais', 'library.troubleshooting': 'Resolução de problemas', 'library.shortcutHint': 'Adição rápida ou arraste ficheiros .chm para aqui', 'library.noMatches': 'Nenhum documento correspondente', 'library.noMatchesDescription': 'Tente outro título, pasta ou caminho.', 'library.searchHelp': 'Ajuda de pesquisa', 'library.clearSearch': 'Limpar pesquisa', 'library.usageGuide': 'Guia do utilizador', 'library.loadFailed': 'Não foi possível carregar a biblioteca', 'library.loadFailedDescription': 'Os dados da biblioteca estão temporariamente indisponíveis.', 'library.reload': 'Recarregar',
  'library.documentCount': '{count} documentos', 'library.filteredCount': '{count} de {total} documentos', 'library.open': 'Abrir {name}', 'library.continue': 'Continuar a ler {name}', 'library.continueLabel': 'Continuar a ler', 'library.sourceMissing': 'Ficheiro de origem em falta', 'library.lastOpened': 'Última abertura: {date}', 'library.addedAt': 'Adicionado em {date}', 'library.remove': 'Remover da biblioteca', 'library.removeNamed': 'Remover {name} da biblioteca', 'library.revealNamed': 'Mostrar {name} no Finder', 'library.reveal': 'Mostrar no Finder', 'library.relinkNamed': 'Voltar a associar o ficheiro de {name}', 'library.relink': 'Voltar a associar ficheiro', 'library.removeConfirm': 'Remover “{name}” da biblioteca? O ficheiro de origem não será eliminado.', 'library.opening': 'A abrir...', 'library.openFailed': 'Não foi possível abrir o CHM: {error}', 'library.loadError': 'Não foi possível carregar os dados da biblioteca: {error}', 'library.importFailed': 'Não foi possível importar os ficheiros CHM', 'library.dropImportFailed': 'Não foi possível importar os ficheiros CHM largados',
  'collection.delete': 'Eliminar coleção', 'collection.deleteNamed': 'Eliminar a coleção {name}', 'collection.deleteConfirm': 'Eliminar a coleção “{name}”?', 'collection.deleteMoveConfirm': 'Eliminar a coleção “{name}”? Os seus {count} documentos serão movidos para Tudo. Os ficheiros de origem não serão eliminados.', 'collection.deleteFailed': 'Não foi possível eliminar a coleção', 'collection.rename': 'Mudar nome da coleção', 'collection.create': 'Nova coleção', 'collection.name': 'Nome da coleção', 'collection.renameAction': 'Mudar nome', 'collection.deleteAction': 'Eliminar', 'collection.submitFailed': 'Não foi possível {action} a coleção: {error}', 'collection.actionRename': 'mudar o nome', 'collection.actionCreate': 'criar',
  'reader.currentBook': 'Livro atual', 'reader.toggleSidebar': 'Mostrar ou ocultar o índice', 'reader.currentMatches': 'Resultados na página atual', 'reader.previousMatch': 'Resultado anterior', 'reader.nextMatch': 'Resultado seguinte', 'reader.previousPage': 'Tópico anterior', 'reader.nextPage': 'Tópico seguinte', 'reader.back': 'Voltar', 'reader.forward': 'Avançar', 'reader.zoomOut': 'Reduzir texto', 'reader.zoomReset': 'Tamanho real', 'reader.zoomIn': 'Ampliar texto', 'reader.encoding': 'Codificação de texto', 'reader.defaultEncoding': 'Codificação predefinida', 'reader.contents': 'Índice', 'reader.directory': 'Índice do documento', 'reader.treeActions': 'Ações do índice', 'reader.expandAll': 'Expandir tudo', 'reader.collapseAll': 'Recolher tudo', 'reader.refreshTree': 'Atualizar índice', 'reader.searchScope': 'Escolher âmbito da pesquisa', 'reader.searchBody': 'Pesquisar no texto', 'reader.searchDirectory': 'Pesquisar no índice', 'reader.body': 'Texto', 'reader.directoryScope': 'Índice', 'reader.chapters': 'Tópicos CHM', 'reader.emptyDirectory': 'Abra um ficheiro CHM para ver\no índice aqui', 'reader.resizeSidebar': 'Redimensionar a barra lateral', 'reader.content': 'Conteúdo do documento', 'reader.emptyTitle': 'Este documento não tem conteúdo', 'reader.emptyDescription': 'Este ficheiro CHM não contém uma página que possa ser apresentada.', 'reader.loading': 'A analisar documento...', 'reader.frameTitle': 'Conteúdo do documento CHM', 'reader.noDirectory': 'Este documento não tem índice\nA página predefinida continua disponível', 'reader.collapseNamed': 'Recolher {name}', 'reader.expandNamed': 'Expandir {name}', 'reader.progress': 'Tópico {current} de {total}', 'reader.topicCount': '{count} tópicos', 'reader.directoryResults': '{count} resultados no índice', 'reader.bodyResults': '{count} resultados em {chapters} tópicos', 'reader.searchFailed': 'A pesquisa no texto falhou: {error}', 'reader.encodingFailed': 'Não foi possível alterar a codificação: {error}', 'reader.openTopicFailed': 'Não foi possível abrir o tópico', 'reader.openExternalFailed': 'Não foi possível abrir a ligação externa',
  'settings.title': 'Definições', 'settings.open': 'Abrir Definições', 'settings.language': 'Idioma', 'settings.languageDescription': 'Escolha o idioma da interface da aplicação.', 'settings.languageZh': 'Chinês simplificado', 'settings.languageEn': 'Inglês', 'settings.appearance': 'Tema de cores', 'settings.appearanceDescription': 'Escolha as cores da biblioteca, definições e leitor.',
  'theme.light': 'Claro', 'theme.lightDescription': 'Cores predefinidas limpas e luminosas', 'theme.warm': 'Quente', 'theme.warmDescription': 'Marfim suave com laranja quente', 'theme.cool': 'Frio', 'theme.coolDescription': 'Azul acinzentado calmo com verde-azulado', 'theme.darkEye': 'Escuro confortável', 'theme.darkEyeDescription': 'Cores escuras de baixa luminosidade com verde suave',
  'error.syncView': 'Não foi possível sincronizar o estado da janela', 'error.reveal': 'Não foi possível mostrar o ficheiro de origem no Finder', 'error.relink': 'Não foi possível voltar a associar o ficheiro de origem', 'error.remove': 'Não foi possível remover o documento da biblioteca',
});

const it = defineTranslations({
  'common.cancel': 'Annulla', 'common.save': 'Salva', 'common.create': 'Crea', 'common.back': 'Indietro',
  'library.title': 'Libreria', 'library.all': 'Tutti', 'library.search': 'Cerca titoli o percorsi', 'library.searchLabel': 'Cerca nella libreria', 'library.viewMode': 'Cambia vista', 'library.grid': 'Vista griglia', 'library.list': 'Vista elenco', 'library.add': 'Aggiungi CHM', 'library.addFiles': 'Aggiungi file CHM', 'library.collections': 'Raccolte della libreria', 'library.newCollection': 'Nuova raccolta',
  'library.dropTitle': 'Rilascia i file CHM per aggiungerli', 'library.dropSubtitle': 'Saranno aggiunti alla raccolta selezionata', 'library.dropInvalidTitle': 'Rilascia solo file CHM', 'library.dropInvalidSubtitle': 'Sono supportati solo documenti .chm', 'library.emptyTitle': 'Questa libreria è vuota', 'library.emptyDescription': 'Aggiungi file CHM locali per organizzarli e leggerli in qualsiasi momento.', 'library.firstUseHelp': 'Per iniziare', 'library.projectReadme': 'Guida al progetto', 'library.installGuide': 'Guida di installazione', 'library.localData': 'Dati locali', 'library.troubleshooting': 'Risoluzione dei problemi', 'library.shortcutHint': 'Aggiunta rapida o trascina qui i file .chm', 'library.noMatches': 'Nessun documento corrispondente', 'library.noMatchesDescription': 'Prova un altro titolo, cartella o percorso.', 'library.searchHelp': 'Guida alla ricerca', 'library.clearSearch': 'Cancella ricerca', 'library.usageGuide': 'Guida utente', 'library.loadFailed': 'Impossibile caricare la libreria', 'library.loadFailedDescription': 'I dati della libreria non sono temporaneamente disponibili.', 'library.reload': 'Ricarica',
  'library.documentCount': '{count} documenti', 'library.filteredCount': '{count} di {total} documenti', 'library.open': 'Apri {name}', 'library.continue': 'Continua a leggere {name}', 'library.continueLabel': 'Continua a leggere', 'library.sourceMissing': 'File originale mancante', 'library.lastOpened': 'Ultima apertura: {date}', 'library.addedAt': 'Aggiunto il {date}', 'library.remove': 'Rimuovi dalla libreria', 'library.removeNamed': 'Rimuovi {name} dalla libreria', 'library.revealNamed': 'Mostra {name} nel Finder', 'library.reveal': 'Mostra nel Finder', 'library.relinkNamed': 'Ricollega il file originale di {name}', 'library.relink': 'Ricollega file originale', 'library.removeConfirm': 'Rimuovere “{name}” dalla libreria? Il file originale non verrà eliminato.', 'library.opening': 'Apertura...', 'library.openFailed': 'Impossibile aprire il CHM: {error}', 'library.loadError': 'Impossibile caricare i dati della libreria: {error}', 'library.importFailed': 'Impossibile importare i file CHM', 'library.dropImportFailed': 'Impossibile importare i file CHM rilasciati',
  'collection.delete': 'Elimina raccolta', 'collection.deleteNamed': 'Elimina la raccolta {name}', 'collection.deleteConfirm': 'Eliminare la raccolta “{name}”?', 'collection.deleteMoveConfirm': 'Eliminare la raccolta “{name}”? I suoi {count} documenti saranno spostati in Tutti. I file originali non verranno eliminati.', 'collection.deleteFailed': 'Impossibile eliminare la raccolta', 'collection.rename': 'Rinomina raccolta', 'collection.create': 'Nuova raccolta', 'collection.name': 'Nome raccolta', 'collection.renameAction': 'Rinomina', 'collection.deleteAction': 'Elimina', 'collection.submitFailed': 'Impossibile {action} la raccolta: {error}', 'collection.actionRename': 'rinominare', 'collection.actionCreate': 'creare',
  'reader.currentBook': 'Libro attuale', 'reader.toggleSidebar': 'Mostra o nascondi l’indice', 'reader.currentMatches': 'Risultati nella pagina corrente', 'reader.previousMatch': 'Risultato precedente', 'reader.nextMatch': 'Risultato successivo', 'reader.previousPage': 'Argomento precedente', 'reader.nextPage': 'Argomento successivo', 'reader.back': 'Indietro', 'reader.forward': 'Avanti', 'reader.zoomOut': 'Riduci testo', 'reader.zoomReset': 'Dimensioni reali', 'reader.zoomIn': 'Ingrandisci testo', 'reader.encoding': 'Codifica testo', 'reader.defaultEncoding': 'Codifica predefinita', 'reader.contents': 'Indice', 'reader.directory': 'Indice del documento', 'reader.treeActions': 'Azioni indice', 'reader.expandAll': 'Espandi tutto', 'reader.collapseAll': 'Comprimi tutto', 'reader.refreshTree': 'Aggiorna indice', 'reader.searchScope': 'Scegli ambito di ricerca', 'reader.searchBody': 'Cerca nel testo', 'reader.searchDirectory': 'Cerca nell’indice', 'reader.body': 'Testo', 'reader.directoryScope': 'Indice', 'reader.chapters': 'Argomenti CHM', 'reader.emptyDirectory': 'Apri un file CHM per vedere\nqui il suo indice', 'reader.resizeSidebar': 'Ridimensiona barra laterale', 'reader.content': 'Contenuto del documento', 'reader.emptyTitle': 'Questo documento non ha contenuto', 'reader.emptyDescription': 'Questo file CHM non contiene una pagina visualizzabile.', 'reader.loading': 'Analisi del documento...', 'reader.frameTitle': 'Contenuto documento CHM', 'reader.noDirectory': 'Questo documento non ha un indice\nLa pagina predefinita è comunque disponibile', 'reader.collapseNamed': 'Comprimi {name}', 'reader.expandNamed': 'Espandi {name}', 'reader.progress': 'Argomento {current} di {total}', 'reader.topicCount': '{count} argomenti', 'reader.directoryResults': '{count} risultati nell’indice', 'reader.bodyResults': '{count} risultati in {chapters} argomenti', 'reader.searchFailed': 'Ricerca nel testo non riuscita: {error}', 'reader.encodingFailed': 'Impossibile cambiare la codifica: {error}', 'reader.openTopicFailed': 'Impossibile aprire l’argomento', 'reader.openExternalFailed': 'Impossibile aprire il link esterno',
  'settings.title': 'Impostazioni', 'settings.open': 'Apri Impostazioni', 'settings.language': 'Lingua', 'settings.languageDescription': 'Scegli la lingua dell’interfaccia dell’applicazione.', 'settings.languageZh': 'Cinese semplificato', 'settings.languageEn': 'Inglese', 'settings.appearance': 'Tema colori', 'settings.appearanceDescription': 'Scegli i colori per libreria, impostazioni e lettore.',
  'theme.light': 'Chiaro', 'theme.lightDescription': 'Colori predefiniti puliti e luminosi', 'theme.warm': 'Caldo', 'theme.warmDescription': 'Avorio tenue con arancione caldo', 'theme.cool': 'Freddo', 'theme.coolDescription': 'Grigio blu tranquillo con verde acqua', 'theme.darkEye': 'Scuro riposante', 'theme.darkEyeDescription': 'Colori scuri a bassa luminosità con verde tenue',
  'error.syncView': 'Impossibile sincronizzare lo stato della finestra', 'error.reveal': 'Impossibile mostrare il file originale nel Finder', 'error.relink': 'Impossibile ricollegare il file originale', 'error.remove': 'Impossibile rimuovere il documento dalla libreria',
});

const ru = defineTranslations({
  'common.cancel': 'Отмена', 'common.save': 'Сохранить', 'common.create': 'Создать', 'common.back': 'Назад',
  'library.title': 'Библиотека', 'library.all': 'Все', 'library.search': 'Поиск по названию или пути', 'library.searchLabel': 'Поиск в библиотеке', 'library.viewMode': 'Изменить вид', 'library.grid': 'Плитка', 'library.list': 'Список', 'library.add': 'Добавить CHM', 'library.addFiles': 'Добавить файлы CHM', 'library.collections': 'Коллекции библиотеки', 'library.newCollection': 'Новая коллекция',
  'library.dropTitle': 'Перетащите файлы CHM для добавления', 'library.dropSubtitle': 'Они будут добавлены в выбранную коллекцию', 'library.dropInvalidTitle': 'Перетащите файлы CHM', 'library.dropInvalidSubtitle': 'Поддерживаются только документы .chm', 'library.emptyTitle': 'Библиотека пуста', 'library.emptyDescription': 'Добавьте локальные файлы CHM, чтобы упорядочить их и читать в любое время.', 'library.firstUseHelp': 'Начало работы', 'library.projectReadme': 'Руководство проекта', 'library.installGuide': 'Установка', 'library.localData': 'Локальные данные', 'library.troubleshooting': 'Устранение неполадок', 'library.shortcutHint': 'Быстрое добавление или перетащите сюда файлы .chm', 'library.noMatches': 'Подходящих документов нет', 'library.noMatchesDescription': 'Попробуйте другое название, папку или путь.', 'library.searchHelp': 'Справка по поиску', 'library.clearSearch': 'Очистить поиск', 'library.usageGuide': 'Руководство пользователя', 'library.loadFailed': 'Не удалось загрузить библиотеку', 'library.loadFailedDescription': 'Данные библиотеки временно недоступны.', 'library.reload': 'Загрузить снова',
  'library.documentCount': 'Документов: {count}', 'library.filteredCount': 'Документов: {count} из {total}', 'library.open': 'Открыть {name}', 'library.continue': 'Продолжить чтение {name}', 'library.continueLabel': 'Продолжить чтение', 'library.sourceMissing': 'Исходный файл отсутствует', 'library.lastOpened': 'Последнее открытие: {date}', 'library.addedAt': 'Добавлено: {date}', 'library.remove': 'Удалить из библиотеки', 'library.removeNamed': 'Удалить {name} из библиотеки', 'library.revealNamed': 'Показать {name} в Finder', 'library.reveal': 'Показать в Finder', 'library.relinkNamed': 'Повторно связать исходный файл {name}', 'library.relink': 'Повторно связать файл', 'library.removeConfirm': 'Удалить «{name}» из библиотеки? Исходный файл не будет удалён.', 'library.opening': 'Открытие...', 'library.openFailed': 'Не удалось открыть CHM: {error}', 'library.loadError': 'Не удалось загрузить данные библиотеки: {error}', 'library.importFailed': 'Не удалось импортировать файлы CHM', 'library.dropImportFailed': 'Не удалось импортировать перетащенные файлы CHM',
  'collection.delete': 'Удалить коллекцию', 'collection.deleteNamed': 'Удалить коллекцию {name}', 'collection.deleteConfirm': 'Удалить коллекцию «{name}»?', 'collection.deleteMoveConfirm': 'Удалить коллекцию «{name}»? Её документы ({count}) будут перемещены в раздел «Все». Исходные файлы не будут удалены.', 'collection.deleteFailed': 'Не удалось удалить коллекцию', 'collection.rename': 'Переименовать коллекцию', 'collection.create': 'Новая коллекция', 'collection.name': 'Название коллекции', 'collection.renameAction': 'Переименовать', 'collection.deleteAction': 'Удалить', 'collection.submitFailed': 'Не удалось {action} коллекцию: {error}', 'collection.actionRename': 'переименовать', 'collection.actionCreate': 'создать',
  'reader.currentBook': 'Текущая книга', 'reader.toggleSidebar': 'Показать или скрыть содержание', 'reader.currentMatches': 'Совпадения на текущей странице', 'reader.previousMatch': 'Предыдущее совпадение', 'reader.nextMatch': 'Следующее совпадение', 'reader.previousPage': 'Предыдущая тема', 'reader.nextPage': 'Следующая тема', 'reader.back': 'Назад', 'reader.forward': 'Вперёд', 'reader.zoomOut': 'Уменьшить текст', 'reader.zoomReset': 'Фактический размер', 'reader.zoomIn': 'Увеличить текст', 'reader.encoding': 'Кодировка текста', 'reader.defaultEncoding': 'Кодировка по умолчанию', 'reader.contents': 'Содержание', 'reader.directory': 'Содержание документа', 'reader.treeActions': 'Действия с содержанием', 'reader.expandAll': 'Развернуть всё', 'reader.collapseAll': 'Свернуть всё', 'reader.refreshTree': 'Обновить содержание', 'reader.searchScope': 'Выбрать область поиска', 'reader.searchBody': 'Искать в тексте', 'reader.searchDirectory': 'Искать в содержании', 'reader.body': 'Текст', 'reader.directoryScope': 'Содержание', 'reader.chapters': 'Темы CHM', 'reader.emptyDirectory': 'Откройте файл CHM, чтобы увидеть\nего содержание здесь', 'reader.resizeSidebar': 'Изменить ширину боковой панели', 'reader.content': 'Содержимое документа', 'reader.emptyTitle': 'В документе нет содержимого', 'reader.emptyDescription': 'В этом файле CHM нет страницы, которую можно показать.', 'reader.loading': 'Анализ документа...', 'reader.frameTitle': 'Содержимое документа CHM', 'reader.noDirectory': 'У документа нет содержания\nСтраница по умолчанию всё ещё доступна', 'reader.collapseNamed': 'Свернуть {name}', 'reader.expandNamed': 'Развернуть {name}', 'reader.progress': 'Тема {current} из {total}', 'reader.topicCount': 'Тем: {count}', 'reader.directoryResults': 'Результатов в содержании: {count}', 'reader.bodyResults': 'Совпадений: {count} в {chapters} темах', 'reader.searchFailed': 'Ошибка поиска в тексте: {error}', 'reader.encodingFailed': 'Не удалось изменить кодировку: {error}', 'reader.openTopicFailed': 'Не удалось открыть тему', 'reader.openExternalFailed': 'Не удалось открыть внешнюю ссылку',
  'settings.title': 'Настройки', 'settings.open': 'Открыть настройки', 'settings.language': 'Язык', 'settings.languageDescription': 'Выберите язык интерфейса приложения.', 'settings.languageZh': 'Упрощённый китайский', 'settings.languageEn': 'Английский', 'settings.appearance': 'Цветовая тема', 'settings.appearanceDescription': 'Выберите цвета библиотеки, настроек и документа.',
  'theme.light': 'Светлая', 'theme.lightDescription': 'Чистые светлые цвета по умолчанию', 'theme.warm': 'Тёплая', 'theme.warmDescription': 'Мягкий оттенок слоновой кости и тёплый оранжевый', 'theme.cool': 'Холодная', 'theme.coolDescription': 'Спокойный серо-синий и бирюзовый', 'theme.darkEye': 'Тёмная для глаз', 'theme.darkEyeDescription': 'Тёмные цвета низкой яркости и мягкий зелёный',
  'error.syncView': 'Не удалось синхронизировать состояние окна', 'error.reveal': 'Не удалось показать исходный файл в Finder', 'error.relink': 'Не удалось повторно связать исходный файл', 'error.remove': 'Не удалось удалить документ из библиотеки',
});

const ar = defineTranslations({
  'common.cancel': 'إلغاء', 'common.save': 'حفظ', 'common.create': 'إنشاء', 'common.back': 'رجوع',
  'library.title': 'المكتبة', 'library.all': 'الكل', 'library.search': 'البحث في العناوين أو المسارات', 'library.searchLabel': 'البحث في المكتبة', 'library.viewMode': 'تغيير طريقة العرض', 'library.grid': 'عرض شبكي', 'library.list': 'عرض قائمة', 'library.add': 'إضافة CHM', 'library.addFiles': 'إضافة ملفات CHM', 'library.collections': 'مجموعات المكتبة', 'library.newCollection': 'مجموعة جديدة',
  'library.dropTitle': 'أفلت ملفات CHM لإضافتها', 'library.dropSubtitle': 'ستُضاف إلى المجموعة المحددة', 'library.dropInvalidTitle': 'أفلت ملفات CHM فقط', 'library.dropInvalidSubtitle': 'يتم دعم مستندات .chm فقط', 'library.emptyTitle': 'هذه المكتبة فارغة', 'library.emptyDescription': 'أضف ملفات CHM المحلية لتنظيمها وقراءتها في أي وقت.', 'library.firstUseHelp': 'بدء الاستخدام', 'library.projectReadme': 'دليل المشروع', 'library.installGuide': 'دليل التثبيت', 'library.localData': 'البيانات المحلية', 'library.troubleshooting': 'استكشاف الأخطاء', 'library.shortcutHint': 'إضافة سريعة أو اسحب ملفات .chm إلى هنا', 'library.noMatches': 'لا توجد مستندات مطابقة', 'library.noMatchesDescription': 'جرّب عنوانًا أو مجلدًا أو مسارًا آخر.', 'library.searchHelp': 'مساعدة البحث', 'library.clearSearch': 'مسح البحث', 'library.usageGuide': 'دليل الاستخدام', 'library.loadFailed': 'تعذر تحميل المكتبة', 'library.loadFailedDescription': 'بيانات المكتبة غير متاحة مؤقتًا.', 'library.reload': 'إعادة التحميل',
  'library.documentCount': '{count} مستندات', 'library.filteredCount': '{count} من {total} مستندات', 'library.open': 'فتح {name}', 'library.continue': 'متابعة قراءة {name}', 'library.continueLabel': 'متابعة القراءة', 'library.sourceMissing': 'ملف المصدر مفقود', 'library.lastOpened': 'آخر فتح: {date}', 'library.addedAt': 'أُضيف في {date}', 'library.remove': 'إزالة من المكتبة', 'library.removeNamed': 'إزالة {name} من المكتبة', 'library.revealNamed': 'إظهار {name} في Finder', 'library.reveal': 'إظهار في Finder', 'library.relinkNamed': 'إعادة ربط ملف المصدر لـ {name}', 'library.relink': 'إعادة ربط ملف المصدر', 'library.removeConfirm': 'هل تريد إزالة «{name}» من المكتبة؟ لن يُحذف ملف المصدر.', 'library.opening': 'جارٍ الفتح...', 'library.openFailed': 'تعذر فتح CHM: {error}', 'library.loadError': 'تعذر تحميل بيانات المكتبة: {error}', 'library.importFailed': 'تعذر استيراد ملفات CHM', 'library.dropImportFailed': 'تعذر استيراد ملفات CHM التي تم إفلاتها',
  'collection.delete': 'حذف المجموعة', 'collection.deleteNamed': 'حذف المجموعة {name}', 'collection.deleteConfirm': 'هل تريد حذف المجموعة «{name}»؟', 'collection.deleteMoveConfirm': 'هل تريد حذف المجموعة «{name}»؟ ستُنقل مستنداتها وعددها {count} إلى الكل، ولن تُحذف ملفات المصدر.', 'collection.deleteFailed': 'تعذر حذف المجموعة', 'collection.rename': 'إعادة تسمية المجموعة', 'collection.create': 'مجموعة جديدة', 'collection.name': 'اسم المجموعة', 'collection.renameAction': 'إعادة تسمية', 'collection.deleteAction': 'حذف', 'collection.submitFailed': 'تعذر {action} المجموعة: {error}', 'collection.actionRename': 'إعادة تسمية', 'collection.actionCreate': 'إنشاء',
  'reader.currentBook': 'الكتاب الحالي', 'reader.toggleSidebar': 'إظهار المحتويات أو إخفاؤها', 'reader.currentMatches': 'نتائج الصفحة الحالية', 'reader.previousMatch': 'النتيجة السابقة', 'reader.nextMatch': 'النتيجة التالية', 'reader.previousPage': 'الموضوع السابق', 'reader.nextPage': 'الموضوع التالي', 'reader.back': 'رجوع', 'reader.forward': 'تقدم', 'reader.zoomOut': 'تصغير النص', 'reader.zoomReset': 'الحجم الفعلي', 'reader.zoomIn': 'تكبير النص', 'reader.encoding': 'ترميز النص', 'reader.defaultEncoding': 'الترميز الافتراضي', 'reader.contents': 'المحتويات', 'reader.directory': 'محتويات المستند', 'reader.treeActions': 'إجراءات المحتويات', 'reader.expandAll': 'توسيع الكل', 'reader.collapseAll': 'طي الكل', 'reader.refreshTree': 'تحديث المحتويات', 'reader.searchScope': 'اختيار نطاق البحث', 'reader.searchBody': 'البحث في النص', 'reader.searchDirectory': 'البحث في المحتويات', 'reader.body': 'النص', 'reader.directoryScope': 'المحتويات', 'reader.chapters': 'موضوعات CHM', 'reader.emptyDirectory': 'افتح ملف CHM لعرض\nمحتوياته هنا', 'reader.resizeSidebar': 'تغيير حجم الشريط الجانبي', 'reader.content': 'محتوى المستند', 'reader.emptyTitle': 'لا يحتوي هذا المستند على محتوى', 'reader.emptyDescription': 'لا يحتوي ملف CHM هذا على صفحة قابلة للعرض.', 'reader.loading': 'جارٍ تحليل المستند...', 'reader.frameTitle': 'محتوى مستند CHM', 'reader.noDirectory': 'لا يحتوي هذا المستند على فهرس\nلا تزال الصفحة الافتراضية متاحة', 'reader.collapseNamed': 'طي {name}', 'reader.expandNamed': 'توسيع {name}', 'reader.progress': 'الموضوع {current} من {total}', 'reader.topicCount': '{count} موضوعات', 'reader.directoryResults': '{count} نتائج في المحتويات', 'reader.bodyResults': '{count} نتائج في {chapters} موضوعات', 'reader.searchFailed': 'فشل البحث في النص: {error}', 'reader.encodingFailed': 'تعذر تغيير ترميز النص: {error}', 'reader.openTopicFailed': 'تعذر فتح الموضوع', 'reader.openExternalFailed': 'تعذر فتح الرابط الخارجي',
  'settings.title': 'الإعدادات', 'settings.open': 'فتح الإعدادات', 'settings.language': 'اللغة', 'settings.languageDescription': 'اختر لغة واجهة التطبيق.', 'settings.languageZh': 'الصينية المبسطة', 'settings.languageEn': 'الإنجليزية', 'settings.appearance': 'سمة الألوان', 'settings.appearanceDescription': 'اختر ألوان المكتبة والإعدادات وقارئ المستندات.',
  'theme.light': 'فاتح', 'theme.lightDescription': 'ألوان افتراضية نظيفة ومشرقة', 'theme.warm': 'دافئ', 'theme.warmDescription': 'عاجي ناعم مع برتقالي دافئ', 'theme.cool': 'بارد', 'theme.coolDescription': 'أزرق رمادي هادئ مع أخضر مزرق', 'theme.darkEye': 'داكن مريح للعين', 'theme.darkEyeDescription': 'ألوان داكنة منخفضة السطوع مع أخضر ناعم',
  'error.syncView': 'تعذرت مزامنة حالة النافذة', 'error.reveal': 'تعذر إظهار ملف المصدر في Finder', 'error.relink': 'تعذرت إعادة ربط ملف المصدر', 'error.remove': 'تعذرت إزالة المستند من المكتبة',
});

const translations: Record<AppLocale, TranslationTable> = {
  'zh-CN': zhCN,
  en,
  'zh-TW': zhTW,
  ja,
  ko,
  es,
  fr,
  de,
  pt,
  it,
  ru,
  ar,
};

export const appMenuLabels: Record<AppLocale, AppMenuLabels> = {
  en: {
    githubRepository: 'GitHub Repository', starOnGitHub: 'Star on GitHub', watchReleases: 'Watch Releases', githubDiscussions: 'GitHub Discussions', releaseFeedback: 'Release Feedback', reportOrRequest: 'Report or Request', reportBug: 'Report a Bug', installHelp: 'Get Install Help', requestFeature: 'Request a Feature', usageQuestion: 'Ask a Usage Question', reportDocumentation: 'Report Documentation', shareReleaseFeedback: 'Share Release Feedback', reportCompatibility: 'Report CHM Compatibility', shareSuccessStory: 'Share a Success Story', securityPolicy: 'Security Policy', reportPerformance: 'Report Performance', reportAccessibility: 'Report Accessibility', reportIssue: 'Report an Issue', supportGuide: 'Support Guide', projectReadme: 'Project README', installGuide: 'macOS Install Guide', privacyAndLocalData: 'Privacy and Local Data', compatibilityNotes: 'Compatibility Notes', troubleshootingGuide: 'Troubleshooting Guide', downloadReleases: 'Download Releases', copyShareText: 'Copy Share Text', copyDiagnosticInfo: 'Copy Diagnostic Info', revealAppDataFolder: 'Reveal App Data Folder', clearExtractedCache: 'Clear Extracted Cache',
  },
  'zh-CN': {
    githubRepository: 'GitHub 仓库', starOnGitHub: '在 GitHub 上点赞', watchReleases: '关注版本发布', githubDiscussions: 'GitHub 讨论区', releaseFeedback: '版本反馈', reportOrRequest: '报告问题或提出建议', reportBug: '报告错误', installHelp: '获取安装帮助', requestFeature: '提出功能建议', usageQuestion: '咨询使用问题', reportDocumentation: '报告文档问题', shareReleaseFeedback: '分享版本反馈', reportCompatibility: '报告 CHM 兼容问题', shareSuccessStory: '分享使用案例', securityPolicy: '安全政策', reportPerformance: '报告性能问题', reportAccessibility: '报告辅助功能问题', reportIssue: '报告问题', supportGuide: '支持指南', projectReadme: '项目说明', installGuide: 'macOS 安装指南', privacyAndLocalData: '隐私与本地数据', compatibilityNotes: '兼容性说明', troubleshootingGuide: '故障排查指南', downloadReleases: '下载版本', copyShareText: '复制分享文案', copyDiagnosticInfo: '复制诊断信息', revealAppDataFolder: '显示应用数据文件夹', clearExtractedCache: '清除解包缓存',
  },
  'zh-TW': {
    githubRepository: 'GitHub 儲存庫', starOnGitHub: '在 GitHub 上按星號', watchReleases: '關注版本發布', githubDiscussions: 'GitHub 討論區', releaseFeedback: '版本意見回饋', reportOrRequest: '回報問題或提出建議', reportBug: '回報錯誤', installHelp: '取得安裝協助', requestFeature: '提出功能建議', usageQuestion: '詢問使用問題', reportDocumentation: '回報文件問題', shareReleaseFeedback: '分享版本意見', reportCompatibility: '回報 CHM 相容性問題', shareSuccessStory: '分享使用案例', securityPolicy: '安全性政策', reportPerformance: '回報效能問題', reportAccessibility: '回報輔助使用問題', reportIssue: '回報問題', supportGuide: '支援指南', projectReadme: '專案說明', installGuide: 'macOS 安裝指南', privacyAndLocalData: '隱私權與本機資料', compatibilityNotes: '相容性說明', troubleshootingGuide: '疑難排解指南', downloadReleases: '下載版本', copyShareText: '複製分享文字', copyDiagnosticInfo: '複製診斷資訊', revealAppDataFolder: '顯示應用程式資料夾', clearExtractedCache: '清除解壓縮快取',
  },
  ja: {
    githubRepository: 'GitHubリポジトリ', starOnGitHub: 'GitHubでスターを付ける', watchReleases: 'リリースをフォロー', githubDiscussions: 'GitHubディスカッション', releaseFeedback: 'リリースのフィードバック', reportOrRequest: '問題報告または要望', reportBug: '不具合を報告', installHelp: 'インストールのヘルプ', requestFeature: '機能をリクエスト', usageQuestion: '使い方を質問', reportDocumentation: '文書の問題を報告', shareReleaseFeedback: 'リリースの感想を共有', reportCompatibility: 'CHM互換性を報告', shareSuccessStory: '活用事例を共有', securityPolicy: 'セキュリティポリシー', reportPerformance: '性能問題を報告', reportAccessibility: 'アクセシビリティ問題を報告', reportIssue: '問題を報告', supportGuide: 'サポートガイド', projectReadme: 'プロジェクト説明', installGuide: 'macOSインストールガイド', privacyAndLocalData: 'プライバシーとローカルデータ', compatibilityNotes: '互換性について', troubleshootingGuide: 'トラブルシューティングガイド', downloadReleases: 'リリースをダウンロード', copyShareText: '共有文をコピー', copyDiagnosticInfo: '診断情報をコピー', revealAppDataFolder: 'アプリデータフォルダを表示', clearExtractedCache: '展開済みキャッシュを消去',
  },
  ko: {
    githubRepository: 'GitHub 저장소', starOnGitHub: 'GitHub에서 별표 주기', watchReleases: '릴리스 팔로우', githubDiscussions: 'GitHub 토론', releaseFeedback: '릴리스 피드백', reportOrRequest: '문제 신고 또는 요청', reportBug: '버그 신고', installHelp: '설치 도움말', requestFeature: '기능 요청', usageQuestion: '사용 방법 질문', reportDocumentation: '문서 문제 신고', shareReleaseFeedback: '릴리스 피드백 공유', reportCompatibility: 'CHM 호환성 신고', shareSuccessStory: '활용 사례 공유', securityPolicy: '보안 정책', reportPerformance: '성능 문제 신고', reportAccessibility: '접근성 문제 신고', reportIssue: '문제 신고', supportGuide: '지원 안내', projectReadme: '프로젝트 안내', installGuide: 'macOS 설치 안내', privacyAndLocalData: '개인정보 및 로컬 데이터', compatibilityNotes: '호환성 안내', troubleshootingGuide: '문제 해결 안내', downloadReleases: '릴리스 다운로드', copyShareText: '공유 문구 복사', copyDiagnosticInfo: '진단 정보 복사', revealAppDataFolder: '앱 데이터 폴더 보기', clearExtractedCache: '압축 해제 캐시 지우기',
  },
  es: {
    githubRepository: 'Repositorio de GitHub', starOnGitHub: 'Dar una estrella en GitHub', watchReleases: 'Seguir versiones', githubDiscussions: 'Debates de GitHub', releaseFeedback: 'Comentarios de la versión', reportOrRequest: 'Informar o solicitar', reportBug: 'Informar de un error', installHelp: 'Obtener ayuda de instalación', requestFeature: 'Solicitar una función', usageQuestion: 'Hacer una pregunta de uso', reportDocumentation: 'Informar sobre la documentación', shareReleaseFeedback: 'Compartir comentarios de la versión', reportCompatibility: 'Informar de compatibilidad CHM', shareSuccessStory: 'Compartir un caso de éxito', securityPolicy: 'Política de seguridad', reportPerformance: 'Informar de rendimiento', reportAccessibility: 'Informar de accesibilidad', reportIssue: 'Informar de un problema', supportGuide: 'Guía de soporte', projectReadme: 'Información del proyecto', installGuide: 'Guía de instalación de macOS', privacyAndLocalData: 'Privacidad y datos locales', compatibilityNotes: 'Notas de compatibilidad', troubleshootingGuide: 'Guía de solución de problemas', downloadReleases: 'Descargar versiones', copyShareText: 'Copiar texto para compartir', copyDiagnosticInfo: 'Copiar información de diagnóstico', revealAppDataFolder: 'Mostrar carpeta de datos', clearExtractedCache: 'Borrar caché extraída',
  },
  fr: {
    githubRepository: 'Dépôt GitHub', starOnGitHub: 'Ajouter une étoile sur GitHub', watchReleases: 'Suivre les versions', githubDiscussions: 'Discussions GitHub', releaseFeedback: 'Avis sur la version', reportOrRequest: 'Signaler ou demander', reportBug: 'Signaler un bogue', installHelp: 'Obtenir de l’aide à l’installation', requestFeature: 'Demander une fonctionnalité', usageQuestion: 'Poser une question d’utilisation', reportDocumentation: 'Signaler un problème de documentation', shareReleaseFeedback: 'Partager un avis sur la version', reportCompatibility: 'Signaler un problème de compatibilité CHM', shareSuccessStory: 'Partager un cas d’utilisation', securityPolicy: 'Politique de sécurité', reportPerformance: 'Signaler un problème de performances', reportAccessibility: 'Signaler un problème d’accessibilité', reportIssue: 'Signaler un problème', supportGuide: 'Guide d’assistance', projectReadme: 'Présentation du projet', installGuide: 'Guide d’installation macOS', privacyAndLocalData: 'Confidentialité et données locales', compatibilityNotes: 'Notes de compatibilité', troubleshootingGuide: 'Guide de dépannage', downloadReleases: 'Télécharger les versions', copyShareText: 'Copier le texte de partage', copyDiagnosticInfo: 'Copier les informations de diagnostic', revealAppDataFolder: 'Afficher le dossier de données', clearExtractedCache: 'Effacer le cache extrait',
  },
  de: {
    githubRepository: 'GitHub-Repository', starOnGitHub: 'Stern auf GitHub vergeben', watchReleases: 'Versionen beobachten', githubDiscussions: 'GitHub-Diskussionen', releaseFeedback: 'Versionsfeedback', reportOrRequest: 'Problem melden oder Wunsch äußern', reportBug: 'Fehler melden', installHelp: 'Installationshilfe erhalten', requestFeature: 'Funktion vorschlagen', usageQuestion: 'Frage zur Nutzung stellen', reportDocumentation: 'Dokumentationsproblem melden', shareReleaseFeedback: 'Versionsfeedback teilen', reportCompatibility: 'CHM-Kompatibilität melden', shareSuccessStory: 'Erfolgsgeschichte teilen', securityPolicy: 'Sicherheitsrichtlinie', reportPerformance: 'Leistungsproblem melden', reportAccessibility: 'Barrierefreiheitsproblem melden', reportIssue: 'Problem melden', supportGuide: 'Support-Leitfaden', projectReadme: 'Projektbeschreibung', installGuide: 'macOS-Installationsanleitung', privacyAndLocalData: 'Datenschutz und lokale Daten', compatibilityNotes: 'Kompatibilitätshinweise', troubleshootingGuide: 'Anleitung zur Fehlerbehebung', downloadReleases: 'Versionen herunterladen', copyShareText: 'Freigabetext kopieren', copyDiagnosticInfo: 'Diagnoseinformationen kopieren', revealAppDataFolder: 'App-Datenordner anzeigen', clearExtractedCache: 'Extraktionscache leeren',
  },
  pt: {
    githubRepository: 'Repositório GitHub', starOnGitHub: 'Dar estrela no GitHub', watchReleases: 'Seguir versões', githubDiscussions: 'Discussões no GitHub', releaseFeedback: 'Comentários da versão', reportOrRequest: 'Comunicar ou pedir', reportBug: 'Comunicar erro', installHelp: 'Obter ajuda de instalação', requestFeature: 'Pedir funcionalidade', usageQuestion: 'Fazer pergunta de utilização', reportDocumentation: 'Comunicar problema na documentação', shareReleaseFeedback: 'Partilhar comentários da versão', reportCompatibility: 'Comunicar compatibilidade CHM', shareSuccessStory: 'Partilhar caso de sucesso', securityPolicy: 'Política de segurança', reportPerformance: 'Comunicar problema de desempenho', reportAccessibility: 'Comunicar problema de acessibilidade', reportIssue: 'Comunicar problema', supportGuide: 'Guia de suporte', projectReadme: 'Descrição do projeto', installGuide: 'Guia de instalação do macOS', privacyAndLocalData: 'Privacidade e dados locais', compatibilityNotes: 'Notas de compatibilidade', troubleshootingGuide: 'Guia de resolução de problemas', downloadReleases: 'Transferir versões', copyShareText: 'Copiar texto de partilha', copyDiagnosticInfo: 'Copiar informações de diagnóstico', revealAppDataFolder: 'Mostrar pasta de dados', clearExtractedCache: 'Limpar cache extraída',
  },
  it: {
    githubRepository: 'Repository GitHub', starOnGitHub: 'Aggiungi una stella su GitHub', watchReleases: 'Segui le versioni', githubDiscussions: 'Discussioni GitHub', releaseFeedback: 'Feedback sulla versione', reportOrRequest: 'Segnala o richiedi', reportBug: 'Segnala un errore', installHelp: 'Ottieni assistenza per l’installazione', requestFeature: 'Richiedi una funzionalità', usageQuestion: 'Fai una domanda sull’uso', reportDocumentation: 'Segnala un problema nella documentazione', shareReleaseFeedback: 'Condividi feedback sulla versione', reportCompatibility: 'Segnala compatibilità CHM', shareSuccessStory: 'Condividi un caso di successo', securityPolicy: 'Politica di sicurezza', reportPerformance: 'Segnala un problema di prestazioni', reportAccessibility: 'Segnala un problema di accessibilità', reportIssue: 'Segnala un problema', supportGuide: 'Guida al supporto', projectReadme: 'Descrizione del progetto', installGuide: 'Guida all’installazione macOS', privacyAndLocalData: 'Privacy e dati locali', compatibilityNotes: 'Note sulla compatibilità', troubleshootingGuide: 'Guida alla risoluzione dei problemi', downloadReleases: 'Scarica versioni', copyShareText: 'Copia testo di condivisione', copyDiagnosticInfo: 'Copia informazioni diagnostiche', revealAppDataFolder: 'Mostra cartella dati app', clearExtractedCache: 'Svuota cache estratta',
  },
  ru: {
    githubRepository: 'Репозиторий GitHub', starOnGitHub: 'Поставить звезду на GitHub', watchReleases: 'Следить за выпусками', githubDiscussions: 'Обсуждения GitHub', releaseFeedback: 'Отзыв о выпуске', reportOrRequest: 'Сообщить или предложить', reportBug: 'Сообщить об ошибке', installHelp: 'Помощь с установкой', requestFeature: 'Предложить функцию', usageQuestion: 'Задать вопрос об использовании', reportDocumentation: 'Сообщить о документации', shareReleaseFeedback: 'Поделиться отзывом о выпуске', reportCompatibility: 'Сообщить о совместимости CHM', shareSuccessStory: 'Поделиться примером использования', securityPolicy: 'Политика безопасности', reportPerformance: 'Сообщить о производительности', reportAccessibility: 'Сообщить о доступности', reportIssue: 'Сообщить о проблеме', supportGuide: 'Руководство поддержки', projectReadme: 'Описание проекта', installGuide: 'Руководство по установке macOS', privacyAndLocalData: 'Конфиденциальность и локальные данные', compatibilityNotes: 'Примечания о совместимости', troubleshootingGuide: 'Руководство по устранению неполадок', downloadReleases: 'Скачать выпуски', copyShareText: 'Копировать текст для публикации', copyDiagnosticInfo: 'Копировать диагностические данные', revealAppDataFolder: 'Показать папку данных приложения', clearExtractedCache: 'Очистить кэш распаковки',
  },
  ar: {
    githubRepository: 'مستودع GitHub', starOnGitHub: 'إضافة نجمة على GitHub', watchReleases: 'متابعة الإصدارات', githubDiscussions: 'مناقشات GitHub', releaseFeedback: 'ملاحظات الإصدار', reportOrRequest: 'إبلاغ أو طلب', reportBug: 'الإبلاغ عن خطأ', installHelp: 'الحصول على مساعدة التثبيت', requestFeature: 'طلب ميزة', usageQuestion: 'طرح سؤال عن الاستخدام', reportDocumentation: 'الإبلاغ عن مشكلة في الوثائق', shareReleaseFeedback: 'مشاركة ملاحظات الإصدار', reportCompatibility: 'الإبلاغ عن توافق CHM', shareSuccessStory: 'مشاركة تجربة ناجحة', securityPolicy: 'سياسة الأمان', reportPerformance: 'الإبلاغ عن مشكلة في الأداء', reportAccessibility: 'الإبلاغ عن مشكلة في إمكانية الوصول', reportIssue: 'الإبلاغ عن مشكلة', supportGuide: 'دليل الدعم', projectReadme: 'نبذة عن المشروع', installGuide: 'دليل تثبيت macOS', privacyAndLocalData: 'الخصوصية والبيانات المحلية', compatibilityNotes: 'ملاحظات التوافق', troubleshootingGuide: 'دليل استكشاف الأخطاء', downloadReleases: 'تنزيل الإصدارات', copyShareText: 'نسخ نص المشاركة', copyDiagnosticInfo: 'نسخ معلومات التشخيص', revealAppDataFolder: 'إظهار مجلد بيانات التطبيق', clearExtractedCache: 'مسح ذاكرة الملفات المستخرجة',
  },
};

export function normalizeLocale(value: string | null | undefined): AppLocale {
  return supportedLocales.includes(value as AppLocale) ? value as AppLocale : 'zh-CN';
}

export function getLocaleDirection(locale: AppLocale): 'ltr' | 'rtl' {
  return locale === 'ar' ? 'rtl' : 'ltr';
}

export function normalizeTheme(value: string | null | undefined): AppTheme {
  return supportedThemes.includes(value as AppTheme) ? value as AppTheme : 'light';
}

export function translate(locale: AppLocale, key: TranslationKey, variables: Record<string, string | number> = {}): string {
  return translations[locale][key].replace(/\{([a-zA-Z]+)\}/g, (match, name: string) => (
    Object.hasOwn(variables, name) ? String(variables[name]) : match
  ));
}

export function getTranslationKeys(): TranslationKey[] {
  return Object.keys(zhCN) as TranslationKey[];
}
